Fencei memory-changing vp for 40x
openhwgroup/core-v-verif pull request #1000
Opened 2021-11-03 14:11 UTC by silabs-robin

This PR adds a virtual peripheral to 40x for testing fencei, as per the vplan.
It listens for a request on the fencei flush interface and then changes the memory for both rtl and iss based on the enable/address/data registers in the vp.
The PR includes a directed test and dv random test for using the vp.

2021-11-03 20:46 UTC, strichmo commented
Thanks @silabs-robin.  A couple of very minor issues to consider.

2021-11-04 12:05 UTC, silabs-robin commented
> Thanks @silabs-robin. A couple of very minor issues to consider.

Hi @strichmo I can't see that there are any other comments than this one? Maybe you wrote about those issues but your text didn't reach github somehow?

2021-11-04 13:01 UTC, strichmo requested changes

2021-11-04 13:01 UTC, strichmo commented
Sorry @silabs-robin I left my comments in pending state.  These should be published now.

2021-11-08 10:01 UTC, silabs-robin commented on cv32e40x/tests/programs/corev-dv/corev_rand_fencei/corev-dv.yaml
>      +rand_stall_obi_disable
The thing is that, with stalls on obi, the tests are sometimes meaningless, IIRC. What I remember is having seen traces where obi stalls allowed for memory to get updated in time before being fetched, so the fence.i became superfluous. That didn't really allow for putting the fence.i functionality to the test.

So the flag was intended to be more than just a turnon thing. But I am not 100% certain that stalls _needs_ to be disabled or whether there could be benefits in having stalls enabled. Though I think that it is most purposeful to have stalls disabled as it is now.

2021-11-08 10:19 UTC, silabs-robin commented on lib/corev-dv/corev_directive_instr.sv
> +  string directive;
Fixed.

(Just copied your comment verbatim.)

2021-11-08 14:45 UTC, strichmo approved these changes

2021-11-08 15:04 UTC, merged