Fencei asserts update
openhwgroup/core-v-verif pull request #1086
Opened 2021-12-27 08:57 UTC by silabs-robin

This PR updates the fencei assertions to keep up with RTL.
One SVA bug was fixed, a cover was made conditionally disabled, and a few additional minor checks were added.
It passes ci_check and the handfull of pma configs that I tried in formal.

NB! I "stole" the `bufferable_in_config` function from a [40x SVA file](https://github.com/openhwgroup/cv32e40x/blob/master/sva/cv32e40x_mpu_sva.sv#L100). Is there any legal issue about this?

2021-12-27 08:58 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> -    // Check that "dm_halt_addr_i" is correct
Moved these to a new file.

2021-12-27 09:00 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_fencei_assert.sv
> +      rvfi_valid [->2:3]  // retire: fencei, (optionally "rvfi_trap"), interrupt/debug handler
It was needed to change `->2` into `->2:3` in the exception case, because certain pma configurations revealed in formal that it is (legally) possible to get a trap on the instruction that follows immediately after a fencei. (So, `fencei-trap-handler`, and not only `fencei-handler`.)

2021-12-27 09:01 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_fencei_assert.sv
> +  if (bufferable_in_config()) begin : gen_c_req_wait_bus
This cover is only reachable in certain pma configurations, so it was conditionally included to avoid benign unreachability errors.

2021-12-27 09:04 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_fencei_assert.sv
> +  a_req_wait_outstanding: assert property (p_req_wait_outstanding)
`a_req_wait_outstanding` should in principle check the same thing as `a_req_wait_bus`, but it is checked via different means because we were in doubt that `a_req_wait_bus` really did check what it is intended to.

`a_outstanding_equivalence` was added as an experiment to track whether the two assertions above remain equivalent as RTL keeps on changing. (It is not a requirement, just a curious check of the asserts themselves.)

2021-12-27 09:04 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_integration_assert.sv
> +module uvmt_cv32e40x_integration_assert
Created a new assert module because there are more signals than just `dm_halt_addr_i` that is speced to have requirements about stability and alignment. I saw some weird counter examples in formal which prompted me to add these.

2021-12-27 17:54 UTC, MikeOpenHWGroup commented
> NB! I "stole" the bufferable_in_config function from a 40x SVA file. Is there any legal issue about this?

There is no legal issue (but thanks for asking).  The CV32E40X is an OpenHW Group "CORE-V" project with the same legal status as the CV32E40P, CV32E40S, CVA6 and CORE-V-VERIF.  That is, all are open-source projects covered by the Sholderpad 2.0 license.  That means _anyone_ may use sources from any of these repostories for _any_ legal purpose, as long as the copywrite is maintained.   So we are good.

2022-01-03 06:10 UTC, silabs-hfegran commented
@silabs-robin, thank you for the updates,
Could you please make sure that the properties are disabled during reset? I foresee that the lack of reset-handling may lead to some issues down the line.

2022-01-03 06:11 UTC, silabs-hfegran requested changes
```
disable iff (!rst_ni)
```

2022-01-03 13:07 UTC, silabs-hfegran approved these changes

2022-01-03 13:07 UTC, merged