Resolve or waive linter issues
openhwgroup/core-v-verif pull request #1089
Opened 2021-12-28 22:40 UTC by MikeOpenHWGroup

This PR resolves and/or waives two distinct linter errors identified by Verissimo:

1. Duplicated code in `lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv`.  Please look at this change carefully. The change is straightforward - two functions have been collapsed into a single function.  Having said that the OBI memory Agent is a critical component in our environments, so we want to be cautious about changes to it.
2. Dealing with `Verissimo SVTB.32.2.0` (Pass strings by reference).  For the most part, these have been waived.

Signed-off-by: Mike Thompson <mike@openhwgroup.org>

2022-01-03 06:50 UTC, silabs-hfegran commented
Thanks @MikeOpenHWGroup 

While you are at it, would you mind removing the superfluous if on line 395 in uvma_obi_memory_drv? (Technically not part of the diff, there is a while contained within an if, checking same condition)

2022-01-03 11:49 UTC, silabs-robin commented on lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv
> +     `uvm_fatal("OBI_MEMORY_DRV", $sformatf("Invalid access_type: %0d", req.access_type))
I might be reading this wrong but the if-condition looks a bit odd to me.
Wouldn't the "uvm_fatal" always be triggered?

2022-01-03 12:05 UTC, silabs-robin commented on cv32e40p/tb/uvmt/uvmt_cv32e40p_iss_wrap.sv
> +    function automatic void split(ref string in_s, ref string s1, s2);
If we heed Verissimo's recommendation, what is the benefit?
I am not so familiar with the pros/cons of this.

There is a potential benefit of less resource use for simulations as they don't have to make copies of all of those strings? But how much of an impact does it make and how beneficial is it?
In certain cases the "input"/"output" designation might be of value?
Some lines might become very long when waiver-comments are appended to them?
I am ok with simply waiving these warnings (maybe even globally) but I don't have a complete view of it.

2022-01-03 12:50 UTC, silabs-hfegran requested changes

2022-01-03 12:50 UTC, silabs-hfegran commented on lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv
> +     `uvm_fatal("OBI_MEMORY_DRV", $sformatf("Invalid access_type: %0d", req.access_type))
Well spotted @silabs-robin

2022-01-03 14:02 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv
> +     `uvm_fatal("OBI_MEMORY_DRV", $sformatf("Invalid access_type: %0d", req.access_type))
Very good eye @silabs-robin, thanks.  I have pushed in a fix.

It turns out, this particular task is _never_ invoked in the CV32E4 environments since the core is always the OBI bus master.

2022-01-03 14:10 UTC, silabs-robin approved these changes

2022-01-03 14:21 UTC, MikeOpenHWGroup commented on cv32e40p/tb/uvmt/uvmt_cv32e40p_iss_wrap.sv
> +    function automatic void split(ref string in_s, ref string s1, s2);
According to the Verissimo documentation on this particular lint check, copying strings in or out of the function's memory space is a significant performance issue.  I have no valid position on that except to observe that copying an entire string will take more time than copying a pointer.  How much of an impact that will be is up for debate, particularly for short strings.

It turns out that in many cases, we pass constant strings to functions and these _cannot_ be passed by reference.  A useless fact about the SV LRM that you can use to impress your friends.  In these cases, I have added a waiver (see [uvmt_cv32e40p_step_compare.sv, line 389](https://github.com/MikeOpenHWGroup/core-v-verif/blob/cv32e40p/dev/cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv#L389) for an example).

> I am ok with simply waiving these warnings (maybe even globally) but I don't have a complete view of it.

I agree that these should be waived globally.  I will discuss with AMIQ as they often have additional insight to these lint errors.  Having said that, they will need a good argument to not add this check to the core-v-verif list of global waivers.  I'll do that on my next pull-request for linter violations.

2022-01-04 13:02 UTC, silabs-hfegran approved these changes

2022-01-04 13:03 UTC, merged