Fixed for addition of PMA integrity bit. Fixed for mimpid pin change
openhwgroup/core-v-verif pull request #1221
Opened 2022-03-03 13:00 UTC by Silabs-ArjanB

Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

2022-03-03 13:07 UTC, Silabs-ArjanB commented
See also https://github.com/openhwgroup/core-v-verif/issues/1222

2022-03-03 13:56 UTC, silabs-hfegran requested changes

2022-03-03 13:56 UTC, silabs-hfegran commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +   $fwrite(fh, $sformatf("--override root/cpu/mimpid=%0d\n", cfg.core_cfg.mimpid_patch));
This is the expected mimpid-value we provide to the ISS, thus it should be a _full_ 32-bit mimpid - in its current form the 4-bit value is cast to a 32 bit value. If the other bits are non-zero this will cause mismatches with what the ISS expects.

In other words, the configuration object  needs to be aware of the full mimpid - ideally we should be able to set that correctly based on the bits that may be overridden combined with what the core is hard coded to. 

-> configuration should set mimpid as a combination of the patch + major +minor-fields.

2022-03-03 13:56 UTC, silabs-hfegran commented on lib/uvm_agents/uvma_core_cntrl/uvma_core_cntrl_cfg.sv
> +      `uvm_field_int(                          mimpid_patch                   , UVM_DEFAULT          )
This reports the current settings to the log/stdout, thus I think it would be better to retain the full mimpid-field here (and optionally add the patch-field to explicitly show what the user set)

2022-03-21 16:19 UTC, MikeOpenHWGroup approved these changes
Looks good to me.  @silabs-hfegran, you should have final sign-off.

2022-03-22 09:43 UTC, silabs-hfegran approved these changes

2022-03-22 09:43 UTC, merged