Use vcs-uvm Makefile target in vcs-gate iss
openhwgroup/core-v-verif pull request #1359
Opened 2022-08-04 09:06 UTC by Gchauvon

Hello,

This PR fixes the vcs-gate target which was broken since the removal of the core only testbench. 
vcs-gate now uses vcs-uvm testbench to run post synthesis simulation. 

We can directly use vcs-uvm Makefile targets and remove old vcs-gate targets.

Guillaume

2022-08-04 13:37 UTC, MikeOpenHWGroup reviewed
This looks good to me @Gchauvon.  However, I currently lack the ability to run with VCS so I will defer to @JeanRochCoulon for a final approval.

2022-08-05 08:46 UTC, ASintzoff requested changes
Is there any need to have configurable `gate_opts` at the moment?
I would suggest to remove them as if we keep it, it will clutter uselessly scripts to configure it.

2022-08-05 13:57 UTC, Gchauvon commented
> Is there any need to have configurable `gate_opts` at the moment? I would suggest to remove them as if we keep it, it will clutter uselessly scripts to configure it.

No there is, indeed, no need for those options for the moment. I removed it. 

@MikeOpenHWGroup, Jean-Roch is in vacation. Since André reviewed the PR. I think you can merge it.

2022-08-05 14:31 UTC, merged

2022-08-05 14:33 UTC, ASintzoff reviewed
LGTM