First version of AXI4 agentPr/axi agent
openhwgroup/core-v-verif pull request #1372
Opened 2022-08-16 08:49 UTC by AEzzejjari

The axi agent can act as a passive or active agent. 
Some assertions are not yet implemented.

2022-09-13 13:10 UTC, MikeOpenHWGroup commented on cva6/env/uvme/uvme_cva6_vsqr.sv
> +   uvma_axi_b_sqr_c      b_sequencer;
Can we prefix all AXI sequencers with "axi_"?  For example, `axi_b_sequencer`.

2022-09-13 13:13 UTC, MikeOpenHWGroup commented on cva6/tb/uvmt/uvmt_cva6_tb.sv
> +     uvm_config_db#(virtual uvma_axi_intf   )::set(.cntxt(null), .inst_name("*"),                   .field_name("axi_vi"),    .value(axi_if));
Typo: the field_name should be `axi_vif`, not `axi_vi`.

2022-09-13 13:18 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_agent.sv
> +   uvma_axi_mem_c      memory;
The memory should be a member of the context, not the agent.

2022-09-13 13:19 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_agent.sv
> +         `uvm_info(get_type_name(), "ACTIVE MODE", UVM_LOW)
Maybe this should be a `uvm_warning` with a message indicating that active mode is not yet implemented.

2022-09-13 13:35 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_ar_agent/uvma_axi_ar_drv.sv
> +               repeat($urandom_range(1, AXI_ARREADY_DLY)) @(posedge this.cntxt.axi_vi.clk);
This is not a good randomization strategy.  The arready_dly should be a random member of a sequence item that the driver uses to determine the the determine the ar_valid to ar_ready cycle delay.   Using $random() messages means we cannot constraint the delay in a testcase.

2022-09-13 13:36 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_ar_agent/uvma_axi_ar_drv.sv
> +         resetn_process();
I am not sure this will work in the general case.   There are two tasks driving ar_ready.  You are assuming that reset happens first, and then never again.

2022-09-13 13:38 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_aw_agent/uvma_axi_aw_drv.sv
> +class uvma_axi_aw_drv_c extends uvm_driver #(uvma_axi_aw_item_c);
Same comments as for the ar_drv

2022-09-13 13:40 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_b_agent/uvma_axi_b_drv.sv
> +         resetn_process();
This assumes reset happens at the beginning of the simulation and then never again.

2022-09-13 13:41 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_w_agent/uvma_axi_w_drv.sv
> +class uvma_axi_w_drv_c extends uvm_driver #(uvma_axi_w_item_c);
Same comments as ar_drv.

2022-09-13 13:43 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/obj/uvma_axi_cfg.sv
> +
Missing field_utils

2022-09-13 14:00 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_ar_item.sv
> +   rand logic [AXI_ID_WIDTH-1:0]   ar_id;
This sequence_item is merely a collection of physical bus signals.  A sequence_item probably does not need to model off of the physical wires of a bus (that is the job of the driver).  More importantly, a sequence item is expected to model the behavior of a bus transaction.  For example, the ready-to-drive delay should be a random member of a sequence item.

Have a look at the `OBI_MEMORY_AGENT` for an example:
- [uvma_obi_memory_if.sv](https://github.com/openhwgroup/core-v-verif/blob/05ba4eb0cf6296bf35f487fbe2ab01e532d0fe26/lib/uvm_agents/uvma_obi_memory/src/uvma_obi_memory_if.sv#L1) is the SystemVerilog interface that models all of the physical OBI ports.
- [uvma_obi_memory_slv_seq_item.sv](https://github.com/openhwgroup/core-v-verif/blob/05ba4eb0cf6296bf35f487fbe2ab01e532d0fe26/lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_slv_seq_item.sv#L28) is sequence item that models an abstraction of an OBI bus cycle.
- [uvma_obi_memory_drv.sv](https://github.com/openhwgroup/core-v-verif/blob/05ba4eb0cf6296bf35f487fbe2ab01e532d0fe26/lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_drv.sv#L353) implements the `drv_mstr_req` task that maps the sequence_item to a bus transaction.

2022-09-13 14:40 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_aw_item.sv
> +class uvma_axi_aw_item_c extends uvm_sequence_item;
Same comments as `ar_item`.

2022-09-13 14:40 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_b_item.sv
> +class uvma_axi_b_item_c extends uvm_sequence_item;
Same comments as `ar_item`.

2022-09-13 14:42 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_b_seq.sv
> +      p_sequencer.b_resp_fifo.get(resp_item);
Where is the sequence item randomized?

2022-09-13 14:42 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_r_item.sv
> +class uvma_axi_r_item_c extends uvm_sequence_item;
Same comments as `ar_item`.

2022-09-13 14:43 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_r_seq.sv
> +      p_sequencer.r_resp_fifo.get(resp_item);
randomized?

2022-09-13 14:43 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_w_item.sv
> +class uvma_axi_w_item_c extends uvm_sequence_item;
Same comments as `ar_item`.

2022-09-13 14:48 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/uvma_axi_aw_assert.sv
> +   cov_awid_x                  : cover property(AXI4_AWID_X);
Coverage of "X" properties.

2022-09-13 14:49 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/uvma_axi_b_assert.sv
> +   cov_bid_x                  : cover property(AXI4_BID_X);
Coverage of "X" properties.

2022-09-13 15:09 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/uvma_axi_mem.sv
> +
Where is the memory?

I would recommend using a sparse memory.   Something like this:
```
bit mem[int unsigned];
```

2022-09-13 15:10 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/uvma_axi_r_assert.sv
> +   property AXI4_RUSEr_STABLE;
Why mixed case?

2022-09-13 15:10 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/uvma_axi_r_assert.sv
> +   cov_rdata_x                : cover property(AXI4_RDATA_X);
Coverage of "X"?

2022-09-13 15:11 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/uvma_axi_w_assert.sv
> +   cov_wdata_x                : cover property(AXI4_WDATA_X);
Coverage of "X"?

2022-09-13 15:32 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_aw_agent/uvma_axi_aw_drv.sv
> +         cntxt.axi_vi.aw_ready <= 0;
I recommend you reference the VIF using its modport.

2022-09-13 15:33 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_ar_agent/uvma_axi_ar_drv.sv
> +               wait(this.cntxt.axi_vi.ar_valid);
I recommend you reference the VIF using its modport.

2022-09-13 15:34 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_b_agent/uvma_axi_b_drv.sv
> +         if(!cntxt.axi_vi.rst_n) begin
I recommend you reference the VIF using its modport.

2022-09-13 15:34 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_w_agent/uvma_axi_w_drv.sv
> +            this.cntxt.axi_vi.w_ready <= 1'b0;
I recommend you reference the VIF using its modport.

2022-09-13 16:45 UTC, MikeOpenHWGroup requested changes
Thanks for this @AEzzejjari, this is a solid contribution.  It is obvious you have studied the core-v-verif structure and worked to fit your implementation to fit - thanks!

I have made a number of specific comments on specific files, please have a look at those.

There are a few things I am worried about:
1. The `sequence_items` are little more than port-for-port models of the physical interface.  This is not what I'd expect to see.  A sequence_item is an abstraction of a transaction.  As such, it does not necessarily need to model all ports of a physical interface and it _does_ need to model things that are not part of the physical interface, but are part of a transaction (e.g. a random req-to-gnt cycle delay).
2. The drivers appear to have a bug in that they assume reset happens at t=0 and then never again.
3. The more I think about it, the less sure I am about the strategy to create an agent for each of the channels.  Please have a look at [uvma_obi_memory_storage_slv_seq.sv](https://github.com/openhwgroup/core-v-verif/blob/05ba4eb0cf6296bf35f487fbe2ab01e532d0fe26/lib/uvm_agents/uvma_obi_memory/src/seq/uvma_obi_memory_storage_slv_seq.sv#L1) so get a sense of how a single Agent needs to handle multiple channels.

Lastly, please consider developing a transaction logger for all of your monitors.  These connect to the monitor's analysis port and write transactions to a logfile in a (hopefully) easy-to-read format.  [uvma_obi_memory_mon_trn_logger.sv](https://github.com/openhwgroup/core-v-verif/blob/05ba4eb0cf6296bf35f487fbe2ab01e532d0fe26/lib/uvm_agents/uvma_obi_memory/src/comps/uvma_obi_memory_mon_trn_logger.sv#L1) is a good example.

2022-09-14 09:46 UTC, AEzzejjari commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_b_seq.sv
> +      p_sequencer.b_resp_fifo.get(resp_item);
The sequence items cannot be randomized because it must contain the response to the request, and this response come from the memory. But, there are some signals for each element that can be randomized like resp and ax_ready.

2022-09-14 13:47 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_b_seq.sv
> +      p_sequencer.b_resp_fifo.get(resp_item);
Got it.   Thanks.

2022-09-26 16:20 UTC, AEzzejjari commented on lib/uvm_agents/uvma_axi/src/comps/uvma_axi_agent.sv
> +   uvma_axi_mem_c      memory;
This modification will be done when we implement the active mode.

2022-09-26 16:21 UTC, AEzzejjari commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_ar_item.sv
> +   rand logic [AXI_ID_WIDTH-1:0]   ar_id;
the sequence item contain all the physical wires of a bus because it used by the monitor. Therefore, if we create a sequence item with signals that model the behavior of a bus transaction, we have to create another sequence items for each channel for sending transaction to other component like coverage models...

2022-09-26 16:24 UTC, AEzzejjari commented on lib/uvm_agents/uvma_axi/src/seq/uvma_axi_r_item.sv
> +class uvma_axi_r_item_c extends uvm_sequence_item;
Same response as b_item

2022-09-26 16:25 UTC, AEzzejjari commented on lib/uvm_agents/uvma_axi/src/uvma_axi_mem.sv
> +
This modification will be done when we implement the active mode in another PR.

2022-09-26 16:28 UTC, AEzzejjari commented
Thanks @MikeOpenHWGroup  for all your comments. 

I have tried to fix what you recommended, except for the stuff that will make many changes in the agent structure and that won't be used for now. We chose to put it in another PR for Active mode.

About the five agent. This will facilitates the reading and comprehension of the agent if anyone want to reuse the agent and it will reduce the complexity of the sequence.

Also for the transaction logger, we choose to implement it in the Active mode PR.

2022-09-27 01:40 UTC, MikeOpenHWGroup commented
Hi @AEzzejjari, I do not see any changes to this PR (maybe I misunderstood).  In its current form, it will be difficult to get this Agent to work.  We should discuss this in person as it will be difficult to resolve in a PR review.

2022-09-27 14:48 UTC, AEzzejjari commented
Hi @MikeOpenHWGroup, here is the change that I have made. Another assertions commit added to cover all the requirements of the AXI4 specification.

2022-09-27 14:59 UTC, MikeOpenHWGroup commented
> Also for the transaction logger, we choose to implement it in the Active mode PR.

This is not a good strategy since the core (CVA6) can be an AXI bus master.

2022-09-28 08:29 UTC, AEzzejjari commented
We can implement the transaction logger in a future PR before the active mode

2023-02-06 09:47 UTC, JeanRochCoulon commented
Closed and replaced by #1606

2023-02-06 09:47 UTC, closed without merging