FRONTEND Vplan edited into VPTOOL
openhwgroup/core-v-verif pull request #1407
Opened 2022-09-06 12:34 UTC by JeanRochCoulon

Please clone the project and execute cva6/docs/VerifPlans/FRONTEND/runme.sh to see the FRONTEND verif plan.
This is a draft version, VPTOOL should be extended to support yaml database. And Verif plan should be reviewed by the team (@ASintzoff, @mike, etc...)

2022-09-06 14:06 UTC, MikeOpenHWGroup requested changes
Please add an SPDX header to all new files.   Is it possible to do this with `pck` files?

2022-09-06 14:06 UTC, MikeOpenHWGroup commented on cva6/docs/VerifPlans/FRONTEND/runme.sh
> +#!/bin/sh
Please add a one-line SPDX header.

2022-09-06 16:19 UTC, MikeOpenHWGroup commented on cva6/docs/VerifPlans/FRONTEND/runme.sh
> +#!/bin/sh
Understood.

2022-09-07 06:42 UTC, zchamski reviewed
Just add the SPDX header on the runme.sh file, otherwise LGTM

2022-09-20 11:28 UTC, MikeOpenHWGroup approved these changes

2022-09-20 11:29 UTC, MikeOpenHWGroup commented
LGTM.   I will leave the final approval and merge to @JeanRochCoulon

2022-09-20 12:37 UTC, MikeOpenHWGroup approved these changes

2022-09-21 13:14 UTC, ASintzoff commented on cva6/docs/VerifPlans/source/dvplan_intro.rst
> +CV32A6 is a standards-compliant 32-bit processor fully compliant with RISC-V specifications: [RVunpriv], [RVpriv] and [RVdbg] and passes [RVcompat] compatibility tests, as requested by [GEN-10] in [C
a standards-compliant 32-bit processor => a 32-bit processor

2022-09-21 13:15 UTC, ASintzoff commented on cva6/docs/VerifPlans/source/dvplan_intro.rst
> +The framework of this document is aligned on the CVA6 design document [CVA6design].
aligned on => aligned with

2022-09-21 13:15 UTC, ASintzoff commented on cva6/docs/VerifPlans/source/dvplan_intro.rst
> +* Module are verified separately
Module are => Modules are

2022-09-21 13:16 UTC, ASintzoff commented on cva6/docs/VerifPlans/source/dvplan_intro.rst
> +* Processor subsystems is split into several modules
subsystems is => subsystems are

2022-09-21 15:35 UTC, JeanRochCoulon commented
Thanks to everyone for feedbacks, it is time to merge !

2022-09-21 15:37 UTC, merged