Cv32e40x/dev idv2
openhwgroup/core-v-verif pull request #1419
Opened 2022-09-20 12:37 UTC by eroom1966

Initial request to merge changes for ImperasDV

2022-09-23 10:59 UTC, silabs-hfegran requested changes

2022-09-23 10:59 UTC, silabs-hfegran commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +      `uvm_info(info_tag, $sformatf("ImperasDV loading test_program %0s", test_program_elf), UVM_NONE)
use UVM_LOW or UVM_MEDIUM for reporting, depending on message "usefulness", I like to use UVM_LOW for things that generally should be reported

2022-09-23 10:59 UTC, silabs-hfegran commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +        `uvm_info(info_tag, "rvviRefInit() succeed", UVM_NONE)
uvm verbosity level,  I like to use UVM_LOW for things that generally should be reported

2022-09-23 10:59 UTC, silabs-hfegran commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +    `uvm_info(info_tag, "ref_init() complete", UVM_NONE)
uvm verbosity level,  I like to use UVM_LOW for things that generally should be reported

2022-09-23 10:59 UTC, silabs-hfegran commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
>        $display("\n%m: *** Test Summary ***\n");
This is apparently not part of this commit, but should also be uvm_info, rather than $display

2022-09-23 10:59 UTC, silabs-hfegran commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +  if (cfg.core_cfg.core_name == "CV32E40X") begin
is this still needed?

2022-09-23 10:59 UTC, silabs-hfegran commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +   //$fwrite(fh, $sformatf("--override %s/nmi_address=0x%08x\n",   refpath, cfg.core_cfg.nmi_addr));
remove commented out code

2022-09-23 10:59 UTC, silabs-hfegran commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +   $fwrite(fh, $sformatf("--override %s/noinhibit_mask=0x%08x\n",                 refpath, cfg.core_cfg.get_noinhibit_mask()));
is this still needed?

2022-09-26 15:19 UTC, silabs-mateilga reviewed
Code in general looks good, apart from a few things commented on. I have not done any test with it yet, I'll comment again when that's done.

2022-09-26 15:19 UTC, silabs-mateilga commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +       //DREQ_NEXT = `DUT_PATH.debug_req_i | (`RVFI_IF.rvfi_dbg==3 && `RVFI_IF.rvfi_dbg_mode);
as above, commented code should be removed or marked with a TODO

2022-09-30 10:52 UTC, Imperas commented on cv32e40x/env/uvme/vseq/uvme_cv32e40x_vp_fencei_tamper_seq.sv
> +  $display("%m addr=0x%08X data=%08X", addr, data);
actually this line was temporary for debug purposes, and lwft in by mistake - so this is removed

2022-09-30 10:54 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +        if(0) $display("RVVI_SET_IRQ %t %0s", $time, `STRINGIFY(``IRQ_NAME)); \
to be modified

2022-09-30 10:58 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +           if (`RVFI_IF.rvfi_rd1_addr==5'(i))            // TODO: originally rvfi_rd_addr
The issue here is that this only allows a single destination register to be written for one instruction retirement, I will make the comment clearer, to indicate this will need updating once the RVFI you have created can describe multiple RD writes

2022-09-30 10:59 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +//   wire [31:0] MIP, MIE, MSTATUS, MCAUSE;
to be removed

2022-09-30 11:00 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +   always @(*) begin: Monitor_RVFI
I will make sure this behaves the same.

2022-09-30 11:05 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +           if (`RVFI_IF.rvfi_dbg_mode && `RVFI_IF.rvfi_dbg=='h3 && intr_intr) begin
to be done

2022-09-30 11:12 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +        `uvm_info(info_tag, "rvviRefInit() succeed", UVM_NONE)
to be changed

2022-09-30 11:12 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
>        $display("\n%m: *** Test Summary ***\n");
to be changed

2022-09-30 11:12 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +    `uvm_info(info_tag, "ref_init() complete", UVM_NONE)
to be changed

2022-09-30 11:23 UTC, Imperas commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +  if (cfg.core_cfg.core_name == "CV32E40X") begin
@MikeOpenHWGroup I cannot comment here this code is nothing to do with my changes.

2022-09-30 11:24 UTC, Imperas commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +   //$fwrite(fh, $sformatf("--override %s/nmi_address=0x%08x\n",   refpath, cfg.core_cfg.nmi_addr));
to be done

2022-09-30 11:25 UTC, Imperas commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +   $fwrite(fh, $sformatf("--override %s/noinhibit_mask=0x%08x\n",                 refpath, cfg.core_cfg.get_noinhibit_mask()));
I suspect not - I will take a look

2022-09-30 11:26 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +//[31:0]         CSR_MSECCFG_ADDR
to be removed

2022-09-30 11:28 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +`define CSR_MCONFIGPTR_ADDR    32'hF15 // huh?
I am not sure where that came from, but I will remove
having said that, although the define for tha CSR address appears it is unused

2022-09-30 11:29 UTC, Imperas commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +       //DREQ_NEXT = `DUT_PATH.debug_req_i | (`RVFI_IF.rvfi_dbg==3 && `RVFI_IF.rvfi_dbg_mode);
to be done

2022-10-03 08:48 UTC, silabs-mateilga commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +           if (`RVFI_IF.rvfi_rd1_addr==5'(i))            // TODO: originally rvfi_rd_addr
The RVFI already does this, with [the rvfi_gpr_*](https://github.com/openhwgroup/cv32e40x/blob/master/bhv/cv32e40x_rvfi.sv#L311) signals.

2022-10-03 17:21 UTC, Imperas commented
Please review changes as requested in earlier messages

2022-10-05 09:38 UTC, silabs-hfegran commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +              `uvm_info(info_tag, $sformatf("RVFI Valid %t", $time), UVM_INFO)
`UVM_INFO`  is not a verbosity level (`UVM_INFO` is a severity level - SV sees both these parameters as pure numbers so this works "by accident" and not by design).

The verbosity level should be something higher than UVM_LOW  if this is code that should only be displayed in the very rare cases where debugging is needed (probably UVM_DEBUG or UVM_HIGH). 

Please avoid unconditional if-expressions, in this case this could be solved by either removing the reporting code altogether or by using a higher verbosity level controlled by the UVM environment.

2022-10-05 09:40 UTC, silabs-hfegran commented on lib/uvm_agents/uvma_rvvi_ovpsim/uvma_rvvi_ovpsim_agent.sv
> +  if (cfg.core_cfg.core_name == "CV32E40X") begin
The question here is if tcontrol_undefined=0 is still needed with updated defaults in the model

2022-10-05 15:33 UTC, eroom1966 commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_imperas_dv_wrap.sv
> +              `uvm_info(info_tag, $sformatf("RVFI Valid %t", $time), UVM_INFO)
as advised using UVM_DEBUG
in addition:
- the net connectivity has been cleaned up
- handling of Instruction Bus Fault, no longer requiring a forced resynchronization

2022-10-12 17:04 UTC, eroom1966 commented
@silabs-mateilga 
I have so far run 450 out of 750 tests and all look good, the change is quite minor, so I am confident of the fix
Can you go ahead and run your testing - you also need to update your ImperasDV-OpenHW as it has changes

2022-10-13 07:38 UTC, silabs-hfegran commented
We need to get moving on this, I would like to get this initial PR merged today. Any potential fall-out should be handled with new bugfix PRs.

@eroom1966, @silabs-mateilga
What are the necessary prerequisites on the infrastructure side to get this up and running at its current state?

2022-10-13 07:39 UTC, silabs-hfegran approved these changes

2022-10-13 07:47 UTC, silabs-mateilga commented
I started up a run late last night, and am about half way through. Nothing surprising yet, other than a severe slow down in simulation time. That could be serverside though, have you noticed anything?

-Marton

From: Lee Moore ***@***.***>
Sent: onsdag 12. oktober 2022 19:04
To: openhwgroup/core-v-verif ***@***.***>
Cc: Marton Teilgard ***@***.***>; Mention ***@***.***>
Subject: Re: [openhwgroup/core-v-verif] Cv32e40x/dev idv2 (PR #1419)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@silabs-mateilga<https://urldefense.com/v3/__https:/github.com/silabs-mateilga__;!!N30Cs7Jr!Sm-FRSjE7eWVJpbuGX0zJIcHolmVw15yHR3lyfP3cR9vyDKx5MFb15mGKDPJSITzn6PaX3FhGfzS9WqR4K8NrZ8$>
I have so far run 450 out of 750 tests and all look good, the change is quite minor, so I am confident of the fix
Can you go ahead and run your testing - you also need to update your ImperasDV-OpenHW as it has changes

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/openhwgroup/core-v-verif/pull/1419*issuecomment-1276482357__;Iw!!N30Cs7Jr!Sm-FRSjE7eWVJpbuGX0zJIcHolmVw15yHR3lyfP3cR9vyDKx5MFb15mGKDPJSITzn6PaX3FhGfzS9WqR19l6Xhw$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AOE32Y7QJVLQPY7IBKMSUJDWC3VQZANCNFSM6AAAAAAQRBA6BM__;!!N30Cs7Jr!Sm-FRSjE7eWVJpbuGX0zJIcHolmVw15yHR3lyfP3cR9vyDKx5MFb15mGKDPJSITzn6PaX3FhGfzS9WqRWuELhSE$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-14 09:03 UTC, merged