FenceiAssert - Check Handshake vs RVFI
openhwgroup/core-v-verif pull request #1514
Opened 2022-11-30 10:10 UTC by silabs-robin

This PR adds one assert to the fencei assertion set.

As mentioned by @silabs-oysteink, there is a problem that the RTL treats `fence` as `fencei`.
The original fencei asserts probed some internal signals and did not double check against RVFI!

@silabs-mateilga, @silabs-krdosvik, @MikeOpenHWGroup, I would appreciate a review and merge. (Very little code to review.)

2022-11-30 10:15 UTC, silabs-mateilga approved these changes
Changes seem correct. Only note I have is that I think the assertion modules should take in the rvfi_instr_if instead of select signals, but I won't make it a requirement for approval.

2022-11-30 10:17 UTC, silabs-oysteink commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
> +
This would correctly check that a fencei_flush_req_o was caused by a fence.i instruction, but it will not check that a fence.i always causes a fencei_flush_req_o ?

2022-11-30 10:25 UTC, Silabs-ArjanB requested changes

2022-11-30 10:25 UTC, Silabs-ArjanB commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
> +  localparam int FENCE_IDATA  = 32'b 000000000000_00000_000_00000_0001111;
Where are the FENCE_IDATA and FENCE_IMASK signals being used? I think it should be checked that the fencei handshake does not occurfor fence instructions (as we know there currently is a bug related to that)

2022-11-30 12:17 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
> +  localparam int FENCE_IDATA  = 32'b 000000000000_00000_000_00000_0001111;
> Where are the FENCE_IDATA and FENCE_IMASK signals being used?

_(I wondered if anyone would ask about this...)_

They were used by me manually in formal, because I needed a temporary constraint to disregard a known-problem CEX.

> I think it should be checked that the fencei handshake does not occurfor fence instructions (as we know there currently is a bug related to that)

I think it is implicitly checked now. If there is a handshake, a `fencei` must retire next (i.e. can't be a `fence`).
But I could add an explicit check too (in case there is some potential path that my human reasoning has overlooked).

The assert catches that bug btw.
A counter-example pops up very fast with exactly that problem.

2022-11-30 12:24 UTC, Silabs-ArjanB commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
> +  localparam int FENCE_IDATA  = 32'b 000000000000_00000_000_00000_0001111;
I would say then to either remove dead code or to use these signals as an extra sanity check for an issue that we know exists in the RTL today.

2022-11-30 12:29 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
>    input wire         data_gnt_i,
(Btw, if we comment in-code, then concluded discussions can be closed as "resolved" and it is easier for "the merge person" to see if anything outstanding was overlooked.)

> Changes seem correct. Only note I have is that I think the assertion modules should take in the rvfi_instr_if instead of select signals, but I won't make it a requirement for approval.

Sure.
When https://github.com/openhwgroup/core-v-verif/pull/1515/files is merged I can (as suggested before) migrate the new helper signals from this file into that shared location and convert to using the interface.

2022-11-30 12:29 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
>    input wire         data_gnt_i,
@silabs-mateilga

2022-11-30 12:43 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
> +  localparam int FENCE_IDATA  = 32'b 000000000000_00000_000_00000_0001111;
> use these signals as an extra sanity check

Done.

2022-12-08 10:24 UTC, silabs-robin commented
> the assertion modules should take in the rvfi_instr_if instead of select signals

I don't think I can prioritize this now. So it would be better to merge.

2022-12-09 12:39 UTC, silabs-robin commented
If there is anything more I should fix, then let me know and I will fix it. (I don't oppose blocking this on rvfi_instr_if, but I will save the energy and not do it until someone hits "request changes" for it.)

If there is nothing more I should fix then please hit "approve" or "merge".

2022-12-09 12:53 UTC, silabs-mateilga commented
> 

As I said in my first comment, I won't block approval for this

2022-12-09 13:00 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_fencei_assert.sv
> +  localparam int FENCE_IDATA  = 32'b 000000000000_00000_000_00000_0001111;
@Silabs-ArjanB if you are happy with the changes, can you update your "requested changes"?

2022-12-09 13:03 UTC, Silabs-ArjanB approved these changes

2022-12-09 14:37 UTC, merged