Xsecure interface integrety
openhwgroup/core-v-verif pull request #1519
Opened 2022-12-01 14:33 UTC by silabs-krdosvik

Passes formal and simulation except debug_test

2022-12-01 14:47 UTC, silabs-krdosvik commented
@silabs-robin @silabs-mateilga When the other PR (bus hardening) is merged (which is not ready yet) I will move the support logic to the support logic module.

2022-12-05 17:36 UTC, MikeOpenHWGroup commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module sl_gnt_error_in_respons
Having more than one module per file is not recommended (see section 1.4 of the [Coding Style Guidelines](https://github.com/openhwgroup/core-v-verif/blob/cv32e40s/dev/docs/CodingStyleGuidelines.md)).  Unless there is a very good reason, please break this module out into its own file (of the same name as the module).

2022-12-06 10:20 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module sl_gnt_error_in_respons
I actually think we might have a very good reason here Mike, let me explain.

This support logic module is meant to contain support logic for several, maybe even all, assertion sets over time. The nature of support logic is small blocks of code, and Kristine has started to organize them in modules, a method of which I approve. If we stick with the Coding Style Guideline of one module per file, we will have a quickly expanding set of files that essentially is submodules to the support_logic module. This might very quickly start cluttering up the /uvmt/ directory, with small modules that essentially all belong in one module. 

I think the best here would be to make an exception to the guideline in one of two ways:
1. Keep the submodules in the uvmt_cv32e0s_support_logic.sv file as is now
2. Gather them in a file called uvmt_cv32e0s_support_logic_submodules.sv

Third option is of course to follow the guideline with one module per file.

I think I'm leaning towards option two here, as the support_logic file might grow in to a massive and confusing beast if it's all in one file.

2022-12-06 10:30 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module sl_gnt_error_in_respons
What about a directory?

```
...tb/uvmt/support_logic/main.sv
...tb/uvmt/support_logic/abc.sv
...tb/uvmt/support_logic/xyz.sv
```

There will be one file per module.
There will be small blocks of code organized in modules.
There will be no clutter in the /uvmt/ directory.

2022-12-06 10:44 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module sl_gnt_error_in_respons
A directory sounds like probably the best option. Honestly, the /uvmt/ directory could do with a few subdirectories in general, at least one for /assert_modules/.

2022-12-06 10:49 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module sl_gnt_error_in_respons
For an assertion modules directory, see https://github.com/openhwgroup/core-v-verif/issues/1406

2022-12-06 12:47 UTC, silabs-mateilga requested changes

2022-12-06 12:47 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module uvmt_cv32e40s_sl_req_setting_in_respons
Could this have a more descriptive name, closer to what it does more than what it's used for? I suggest something like  `uvmt_cv32e40s_addr_ph_attribute_fifo`, as the functionality is to track an attribute of a address phase for checking with the corresponding response phase.

Also, these modules should have a good description in comments. This is especially important in support logic, as the goal is to make reuse easy.

2022-12-06 12:47 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module uvmt_cv32e40s_sl_req_gntpar_error_in_resp
Try to reuse the module above, as this seems like just a special case of that module.

2022-12-06 12:47 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +    output logic setting_in_respons
As with the name change suggested, this name should probably be changed as well, as the actual stored data shown is what was recorded in the address phase. Maybe "attr_in_addrph"(attr for attribute), or maybe "attr_in_outstanding_txn"?

2022-12-06 12:47 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
> +   logic is_store_in_respons_data;
I see you are using the keyword "respons" to mean "response phase" quite a bit. I think this is a bit Norwegian sounding, and may be a bit confusing for international users. I suggest "resp_ph" or "resp_phase" as alternatives.

2022-12-06 12:47 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    //Make sure the checksum dont matches the content
Comment should probably indicate "checksum correctness", not that it "doesn't match the content"

2022-12-06 12:47 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +  sequence seq_address_phase_checksum(achk, addr, prot, memtype, be, we, dbg, atop, wdata);
As this isn't a sequence of events, I'd suggest assigning this value to a signal instead.

2022-12-06 12:47 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
General comment to this file: A few of these asserts, especially related to alerts and checksum errors, are situations that are only possible through cutpoints and driving signals to values they logically can't reach. These asserts will give "cover not met" in formal for tests that don't force the error, if the rtl is clean. Each of these asserts should have a clear warning in the comments, to avoid unaware engineers wasting time debugging them.

2022-12-12 14:12 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
That is a good point! It might be a bit messy, but Ill fix this in the PR: https://github.com/openhwgroup/core-v-verif/pull/1538, as I have already done a general cleanup there. (By doing it in the other PR, I hope that the merge will be less stressful)

2022-12-12 14:13 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +  sequence seq_address_phase_checksum(achk, addr, prot, memtype, be, we, dbg, atop, wdata);
True! Will fix it! :-)

2022-12-13 15:42 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module uvmt_cv32e40s_sl_req_setting_in_respons
WIll change! And make descriptive comments!

2022-12-13 15:43 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +    output logic setting_in_respons
Changed! :-)

2022-12-13 15:44 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_tb_ifs.sv
> +   logic is_store_in_respons_data;
respons is changed to the correct English word: response. I use response and not response phase, as the response is the specific packet, while response phase is all the clock cycles from a valid response is formed untill it is accepted.

2022-12-13 15:45 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module uvmt_cv32e40s_sl_req_gntpar_error_in_resp
Yess! I will try :-)

2022-12-13 15:46 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_support_logic.sv
> +module sl_gnt_error_in_respons
Agreed! Ill make a folder then! :-)

2022-12-14 12:56 UTC, closed without merging

2022-12-14 12:57 UTC, silabs-krdosvik commented
I made a new PR (https://github.com/openhwgroup/core-v-verif/pull/1542) because of some git rebase trouble.