CSR hardening update, because rtl is updated
openhwgroup/core-v-verif pull request #1547
Opened 2022-12-16 13:50 UTC by silabs-krdosvik

RTL is updated, so must the assertions.
Change: take into account the reset value of a CSR register when shadowing the CSR.

2022-12-16 14:11 UTC, silabs-halfdan requested changes

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    ~xsecure_if.core_i_cs_registers_i_jvt_csr_i_rdata_q == (~cv32e40s_pkg::CSR_JVT_MASK & ~RESET_VALUE_0) | (cv32e40s_pkg::CSR_JVT_MASK & xsecure_if.core_cs_registers_jvt_csr_gen_hardened_shadow_q)
Add parenthesis to ensure a precise understanding of the expression, at least encasing the right side of "==".

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    and ~xsecure_if.core_i_cs_registers_i_mstatus_csr_i_rdata_q == (~cv32e40s_pkg::CSR_MSTATUS_MASK & ~cv32e40s_pkg::MSTATUS_RESET_VAL) | (cv32e40s_pkg::CSR_MSTATUS_MASK & xsecure_if.core_cs_register
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    and ~xsecure_if.core_i_cs_registers_i_xsecure_cpuctrl_csr_i_rdata_q == (~cv32e40s_pkg::CSR_CPUCTRL_MASK & ~cv32e40s_pkg::CPUCTRL_RESET_VAL) | (cv32e40s_pkg::CSR_CPUCTRL_MASK & xsecure_if.core_cs_
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    and ~xsecure_if.core_i_cs_registers_i_dcsr_csr_i_rdata_q == (~cv32e40s_pkg::CSR_DCSR_MASK & ~cv32e40s_pkg::DCSR_RESET_VAL) | (cv32e40s_pkg::CSR_DCSR_MASK & xsecure_if.core_cs_registers_dcsr_csr_g
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    and ~xsecure_if.core_i_cs_registers_i_mepc_csr_i_rdata_q == (~cv32e40s_pkg::CSR_MEPC_MASK & ~RESET_VALUE_0) | (cv32e40s_pkg::CSR_MEPC_MASK & xsecure_if.core_cs_registers_mepc_csr_gen_hardened_sha
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    and ~xsecure_if.core_i_cs_registers_i_mscratch_csr_i_rdata_q == (~cv32e40s_pkg::CSR_MSCRATCH_MASK & ~RESET_VALUE_0) | (cv32e40s_pkg::CSR_MSCRATCH_MASK & xsecure_if.core_cs_registers_mscratch_csr_
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +      ~xsecure_if.dut_wrap_cv32e40s_wrapper_core_cs_registers_csr_pmp_pmp_mseccfg_csr_i_rdata_q == (~cv32e40s_pkg::CSR_MSECCFG_MASK & ~cv32e40s_pkg::MSECCFG_DEFAULT) | (cv32e40s_pkg::CSR_MSECCFG_MASK
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +      ~xsecure_if.dut_wrap_cv32e40s_wrapper_i_core_i_cs_registers_i_csr_pmp_gen_pmp_csr_n_pmp_region_pmpncfg_csr_i_rdata_q[n] == (~cv32e40s_pkg::CSR_PMPNCFG_MASK & ~cv32e40s_pkg::PMPNCFG_DEFAULT) | (
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +      and ~xsecure_if.dut_wrap_cv32e40s_wrapper_i_core_i_cs_registers_i_csr_pmp_gen_pmp_csr_n_pmp_region_pmp_addr_csr_i_rdata_q[n] == (~cv32e40s_pkg::CSR_PMPADDR_MASK[PMP_ADDR_WIDTH-1:0] & ~RESET_VAL
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +        ~xsecure_if.dut_wrap_cv32e40s_wrapper_i_core_i_cs_registers_i_smclic_csrs_mtvt_csr_i_rdata_q == (~cv32e40s_pkg::CSR_MTVT_MASK & ~cv32e40s_pkg::MTVT_RESET_VAL) | (cv32e40s_pkg::CSR_MTVT_MASK &
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +        and ~xsecure_if.dut_wrap_cv32e40s_wrapper_i_core_i_cs_registers_i_smclic_csrs_mtvec_csr_i_rdata_q == (~cv32e40s_pkg::CSR_MTVEC_CLIC_MASK & ~cv32e40s_pkg::MTVEC_CLIC_RESET_VAL) | (cv32e40s_pkg
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +        and ~xsecure_if.dut_wrap_cv32e40s_wrapper_i_core_i_cs_registers_i_smclic_csrs_mintstatus_csr_i_rdata_q == (~cv32e40s_pkg::CSR_MINTSTATUS_MASK & ~cv32e40s_pkg::MINTSTATUS_RESET_VAL) | (cv32e40
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +        and ~xsecure_if.dut_wrap_cv32e40s_wrapper_i_core_i_cs_registers_i_smclic_csrs_mintthresh_csr_i_rdata_q == (~CSR_MINTTHRESH_MASK & ~RESET_VALUE_0) | (CSR_MINTTHRESH_MASK & xsecure_if.dut_wrap_
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +        ~xsecure_if.dut_wrap_cv32e40s_wrapper_core_cs_registers_basic_mode_csrs_mtvec_csr_rdata_q == (~cv32e40s_pkg::CSR_MTVEC_BASIC_MASK & ~cv32e40s_pkg::MTVEC_BASIC_RESET_VAL) | (cv32e40s_pkg::CSR_
Parenthesis

2022-12-16 14:11 UTC, silabs-halfdan commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +        and ~xsecure_if.dut_wrap_cv32e40s_wrapper_core_cs_registers_basic_mode_csrs_mie_csr_rdata_q == (~cv32e40s_pkg::IRQ_MASK & ~RESET_VALUE_0) | (cv32e40s_pkg::IRQ_MASK & xsecure_if.dut_wrap_cv32e
Parenthesis

2022-12-16 14:24 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert.sv
> +    ~xsecure_if.core_i_cs_registers_i_jvt_csr_i_rdata_q == (~cv32e40s_pkg::CSR_JVT_MASK & ~RESET_VALUE_0) | (cv32e40s_pkg::CSR_JVT_MASK & xsecure_if.core_cs_registers_jvt_csr_gen_hardened_shadow_q)
Aaa, I see, I didnt know, so thanks!! Okei, all the parentheses are now added :-)

2022-12-16 15:03 UTC, merged

2022-12-19 06:39 UTC, Silabs-ArjanB commented
Merged and then reverted again by https://github.com/openhwgroup/core-v-verif/pull/1548 as the initial PR was not complete yet.

2022-12-19 08:00 UTC, silabs-halfdan reviewed
Approving.