PMA Assert - Add Missing Asserts
openhwgroup/core-v-verif pull request #1686
Opened 2023-02-28 12:01 UTC by silabs-robin

This PR adds assertions for the PMA based on what the link-to-coverage in the vplan revealed to be missing.

Test status:
* ci_check - Passes 7/12 
* Fv default - Passes (except 2 slow/non-converging)
* Fv pma 1/2/.../5 - (Same as for Fv default)

2023-02-28 12:06 UTC, silabs-robin commented on mk/uvmt/xrun.mk
> +XRUN_COMP_FLAGS += -setenv CADENCE_ENABLE_AVSREQ_63188_PHASE_1=1
Same as the above "Value Parameters" option, but for "Type Parameters".

This makes Xcelium behave LRM-compliant.
(Their explanation for why it is not default is that _"users may prefer that this issue should be reported during compilation stage and not later during elab"_, but it actually means that some checking will never happen at all.)

2023-02-28 12:11 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
> +  // Mem accesses reflect actual bus
Also, because some checking relies on RVFI, added a check that RVFI truthfully represent OBI bus transactions.

See https://github.com/openhwgroup/cv32e40s/issues/410

2023-02-28 12:12 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
> +  ) else `uvm_error(info_tag, "TODO");
Woops! This lacks a uvm_error message. I will fix it. _(But I will wait until some more feedback accumulates so I can do it all in one go.)_

2023-02-28 12:14 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_assumes.sv
> +  uvmt_cv32e40s_support_logic_for_assert_coverage_modules_if.slave_mp  sup
Please use more descriptive name than "sup" - maybe support_if / support_if_mp etc.

2023-02-28 12:14 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +  uvmt_cv32e40s_support_logic_for_assert_coverage_modules_if.slave_mp  sup,
"sup", as comment above

2023-02-28 12:16 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_assumes.sv
> +module  uvmt_cv32e40s_assumes (
Note: I am adding assumes. Please review thoroughly. (I think they are reasonable and safe.)

2023-02-28 12:16 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +    (core_trans_i.addr inside {[DM_REGION_START:DM_REGION_END]})
is DM_REGION_END inclusive?

2023-02-28 12:23 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +    (1, addr = bus_trans_o.addr)
This may lead to unnecessary sampling, as ##0 (1, ... ) might always be sampled (tool dependent), then discarded if not matching forked stream.  (And will most likely generate warning about false positives in formal verification tools)

Safer to use
```
(bus_trans_valid_o && bus_trans_ready_i,
 addr = bus_trans_o.addr)
 ```

2023-02-28 12:23 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
> +  ) else `uvm_error(info_tag, "TODO");
Missing message?

2023-02-28 12:24 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
> +    for (int i = 0; i < 16/*NMEM*/; i++) begin
NMEM means? use constant/define instead?

2023-02-28 12:26 UTC, silabs-hfegran requested changes
Mostly code-readability/maintainability issues and some questions, please se my other comments above

2023-02-28 12:31 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_assumes.sv
> +  uvmt_cv32e40s_support_logic_for_assert_coverage_modules_if.slave_mp  sup
I think that 1) the support interface is so famous now that it comes to mind easily, 2) it isn't even necessary to understand what it stands for because all the usage of it calls upon the more descriptive and understandable names within it, and 3) long prefixes makes the already-difficult-to-read properties even more difficult to read.

On point 3, this is similar to `import numpy as np` which is very common. Even a very simple expression like `a && !(b || c)` has a clearer logic than `my_interface_name.descriptive_name_a && !(my_interface_name.descriptive_name_b || my_interface_name.descriptive_name_c)`.

I can change the code if that is what the majority of people prefer.

2023-02-28 12:45 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +    (core_trans_i.addr inside {[DM_REGION_START:DM_REGION_END]})
It doesn't say so explicitly in the UM, AFAICT.
But the default values suggest that they are, because they are defined like this:

```
    .DM_REGION_START          (     32'hF0000000 ),
    .DM_REGION_END            (     32'hF0003FFF ),
```

@Silabs-ArjanB is DM_REGION_END inclusive?

2023-02-28 12:47 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_assumes.sv
> +  uvmt_cv32e40s_support_logic_for_assert_coverage_modules_if.slave_mp  sup
The problem is not in its instantiation where you can figure out what the port is based on its type. 
When you read the code where it is used, it would be much more readable for someone not intimately familiar with our source code and avoid having to cross reference to type then figure out its use. A lot of code is not read top to bottom, but rather start at the point of seeing some issue.
Reading the source code and seeing "sup" means I have to find instantiation, and see what kind of type this is, see that this is a modport in some interface that is called support logic and then deduce that this is the support logic interface.
If the signal was called something like support_if or support_logic_if it would be immediately apparent that this is the support logic interface instance. (Not to mention that our coding guidelines warrant an _if for interface instances and _if_t for interface types)

I had to stop and actually think for a bit to figure out what this actually is, even when just reading the port list.

2023-02-28 14:43 UTC, silabs-robin commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +endfunction : is_pma_fault
Fixed.

2023-02-28 14:43 UTC, silabs-robin commented on mk/uvmt/xrun.mk
> +XRUN_COMP_FLAGS += -setenv CADENCE_ENABLE_AVSREQ_63188_PHASE_1=1
Hiding, as reviewers probably have read it already.

2023-02-28 14:44 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
> +  // Mem accesses reflect actual bus
Hiding, as reviewers probably have read it already.

2023-02-28 14:44 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
> +  ) else `uvm_error(info_tag, "TODO");
Fixed.

2023-02-28 14:44 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +// Copyright 2023 Silicon Labs, Inc.
Hiding, as reviewers probably have read it already.

2023-02-28 14:44 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_assumes.sv
> +  uvmt_cv32e40s_support_logic_for_assert_coverage_modules_if.slave_mp  sup
Fixed.

2023-02-28 14:44 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +    bus_trans_o.memtype[0] == bus_trans_bufferable
Fixed.

2023-02-28 14:50 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +    (1, addr = bus_trans_o.addr)
Fixed.

2023-02-28 14:50 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_rvfi_assert.sv
> +  ) else `uvm_error(info_tag, "TODO");
Fixed.

2023-02-28 14:51 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +  uvmt_cv32e40s_support_logic_for_assert_coverage_modules_if.slave_mp  sup,
Fixed.

2023-02-28 14:56 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_assumes.sv
> +module  uvmt_cv32e40s_assumes (
These assumes are global and unconditionally included.

2023-03-02 08:32 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_pma_assert.sv
> +    (core_trans_i.addr inside {[DM_REGION_START:DM_REGION_END]})
Got confirmation in chat. The answer is yes, start/end is inclusive.

2023-03-02 09:01 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_assumes.sv
> +module  uvmt_cv32e40s_assumes (
I know that these assumes were necessary before. But I cannot reproduce it (and I've tried a lot).
Either my code got tweaked during development, or something in the environment changed when I pulled the latest from upstream.

In any case, they are not necessary anymore so I have deleted them.

2023-03-02 13:20 UTC, silabs-hfegran approved these changes

2023-03-07 07:26 UTC, merged