CVXIF Coverage model
openhwgroup/core-v-verif pull request #1691
Opened 2023-03-02 08:38 UTC by AyoubJalali

2023-03-02 13:48 UTC, AyoubJalali commented
I add in the last commit the macros file, and ofc including the file in pkg

2023-03-02 15:42 UTC, MikeOpenHWGroup reviewed
LGTM @AyoubJalali.  I will defer to @ASintzoff for final approval and merge.

2023-03-03 10:44 UTC, ASintzoff requested changes
Minor changes requested (see comments in files).

2023-03-03 10:44 UTC, ASintzoff commented on lib/uvm_agents/uvma_cvxif/src/uvma_cvxif_macros.sv
> +// Copyright 2023 Datum Technology Corporation
You should keep the original year in the copyrights and add `// Copyright 2023 Thales DIS`.

2023-03-03 10:44 UTC, ASintzoff commented on lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_cov_model.sv
> +							  (binsof(cp_writeback) intersect{1} ||
Could you replace tabs by spaces?

Please note this should done at multiple places in this file (perhaps in other ones also).

2023-03-03 14:25 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_cvxif/src/comps/uvma_cvxif_cov_model.sv
> +							  (binsof(cp_writeback) intersect{1} ||
100% agree about the spaces.  Tabs are expressly forbidden in our [Coding Style Guidelines](https://github.com/openhwgroup/core-v-verif/blob/master/docs/CodingStyleGuidelines.md), see sction 1.2.2.

2023-03-07 09:09 UTC, merged