Add new mechanism of the end of test for generated tests
openhwgroup/core-v-verif pull request #1706
Opened 2023-03-08 10:39 UTC by AyoubJalali

Hello, I add in the [cva6_asm_program_gen.sv](https://github.com/openhwgroup/core-v-verif/blob/cva6/dev/cva6/env/corev-dv/cva6_asm_program_gen.sv) file, the gen_test_done function to implement the new end of test mechanism, so to use it you should add in the cmd line : **--sim_opts="+uvm_set_inst_override=riscv_asm_program_gen,cva6_asm_program_gen_c,'uvm_test_top.asm_gen'"** to override the original RISCV-DV class with the new one.

2023-03-08 14:00 UTC, MikeOpenHWGroup requested changes

2023-03-08 14:00 UTC, MikeOpenHWGroup commented on cva6/env/corev-dv/cva6_asm_program_gen.sv
> +      instr_stream.push_back({indent, "j wait"});
This will create a fast-running loop of jump instructions which will pollute the tracefiles with unnecessary entries at the end.  Better to use a `wfi` instruction (and ensure that no further interrupts are generated).

2023-03-08 14:03 UTC, zchamski requested changes

2023-03-08 15:15 UTC, MikeOpenHWGroup commented
Hi @zchamski, yes, I am aware of this and have asked for it to be updated.  The tight-loop end-of-test-program is bad practise.  Adding an uncontrolled delay "to accommodate the completion of AXI bursts", etc. is also a very bad practise.

We need to transition the CVA6 testbench in CORE-V-VERIF to properly use the UVM run-flow for test-case control.  In UVM, all active agents will signal to the environment when they think the simulation can end.  In CORE-V-VERIF, the test-program does this by writing a specific value `tohost` and when halting program execution using wfi.  The environment sees that the test-program wants to stop the simulation, but will not do so until all other components have signalled their agreement.  (This is called "dropping their objection" in UVM-ese.

We have not integrated the AXI Agent yet, so we should consider some sort of temporary measure such that the testbench waits for completion of AXI bursts before terminating the simulation.

2023-03-09 11:07 UTC, zchamski commented
Hi @MikeOpenHWGroup , 

> We need to transition the CVA6 testbench in CORE-V-VERIF to properly use the UVM run-flow for test-case control.

This is being worked on with good progress (`$finish` called from `".../uvm_top.h", line 61`...)  Still to do: handle test result at UVM toplevel.

2023-03-23 11:40 UTC, AyoubJalali commented
@zchamski I don't think there is a  need to distinguish between PASS and FAIL states for RISCV-DV, I'm not sure but it's gonna cause any problems in future use

2023-03-23 16:26 UTC, MikeOpenHWGroup commented on cva6/env/corev-dv/cva6_asm_program_gen.sv
> +      instr_stream.push_back({indent, "li gp, 1"});
Actually, @zchamski, except in some very special cases, a test-program generated by `riscv-dv` cannot "know" if it passes or fails because it is merely a stream of pseudo-random instructions with no purpose.  When running such test-programs the result must be compared against a reference model.

2023-03-23 16:27 UTC, MikeOpenHWGroup commented
I have approved this PR, but will not merge until @zchamski has had a chance to comment on the responses from @AyoubJalali and I.

2023-03-24 15:42 UTC, zchamski commented
> @zchamski I don't think there is a need to distinguish between PASS and FAIL states for RISCV-DV, I'm not sure but it's gonna cause any problems in future use

@AyoubJalali , I agree that the generated tests are not self-checking and therefore, they do not raise error conditions.  We can simply assume that reaching the end of the test program is a success in itself and always return 0.  This approach is not likely to cause any harm in the future (not until we start generating self-checking test programs.)

2023-03-24 15:52 UTC, zchamski commented
@MikeOpenHWGroup , the jump-to-self loop at the end of execution will be needed as long as we run Spike in single (non-tandem) mode.  It is the only compact (and easily trackable) way to give Spike a chance to detect the test termination condition, since it may need up to 5000 instruction executions to respond to a change in `tohost` value.

As soon as the tandem mode is on place, there will be no such "up to 5000 instructions" latency anymore, and we could then reconsider the need for the jump-to-self loop.

2023-03-24 15:53 UTC, MikeOpenHWGroup commented
> This approach is not likely to cause any harm in the future (not until we start generating self-checking test programs.)

For that, we will need to have the ability to signal a failure from a test-program.  The E40 cores already provide an example of how to do that.  It is a simple extension of what we have in this PR.

2023-03-24 15:54 UTC, MikeOpenHWGroup commented on cva6/env/corev-dv/cva6_asm_program_gen.sv
> +      instr_stream.push_back({indent, "li gp, 1"});
Can we resolve this conversation now?

2023-03-24 15:57 UTC, zchamski commented on cva6/env/corev-dv/cva6_asm_program_gen.sv
> +      instr_stream.push_back({indent, "j wait"});
We cannot use `wfi` on CVA6 because it is marked as *invalid instruction* in several situations (cf. the instruction decoder).

2023-03-24 16:01 UTC, zchamski approved these changes

2023-03-24 16:03 UTC, zchamski commented on cva6/env/corev-dv/cva6_asm_program_gen.sv
> +      instr_stream.push_back({indent, "li gp, 1"});
Definitely yes.

2023-03-24 16:04 UTC, zchamski commented
> > This approach is not likely to cause any harm in the future (not until we start generating self-checking test programs.)
> 
> For that, we will need to have the ability to signal a failure from a test-program. The E40 cores already provide an example of how to do that. It is a simple extension of what we have in this PR.

We already have this capability with the values written into `tohost` : any value in bits [31:1] that is different from 0 is treated as a failure code.

2023-03-24 20:22 UTC, MikeOpenHWGroup approved these changes

2023-03-24 20:22 UTC, merged