corrected typo
openhwgroup/core-v-verif pull request #1714
Opened 2023-03-10 14:01 UTC by XavierAubert

I added a small warning before doing the PR, and of course I made a mistake...

2023-03-10 16:23 UTC, MikeOpenHWGroup requested changes

2023-03-10 16:23 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/custom/isa/custom/riscv_custom_instr.sv
> +    $warning("convert2bin has only been partially implemented for XPULP Instructions");
Please use `uvm_warning()` for these types of messages.  (I should have caught that the first time.)

2023-03-13 17:59 UTC, XavierAubert commented on cv32e40p/env/corev-dv/custom/isa/custom/riscv_custom_instr.sv
> +    $warning("convert2bin has only been partially implemented for XPULP Instructions");
```suggestion
     `uvm_warning("COREV-DV", "convert2bin has only been partially implemented for XPULP Instructions")
```

2023-03-13 20:07 UTC, MikeOpenHWGroup approved these changes

2023-03-13 20:07 UTC, merged