UVM test termination: Use end-of-test output of RVFI tracer iso. $finish.
openhwgroup/core-v-verif pull request #1729
Opened 2023-03-18 13:46 UTC by zchamski

This is a companion PR to cva6 PR https://github.com/openhwgroup/cva6/pull/1125.  It propagates the end-of-test information to the UVM testbench and adds a basic interpretation of the test exit code.

Note: this PR also reduces the severity of the absence of fetch toggle in CVA6 from ERROR to WARNING.  Using ERROR severity resulted in non-zero error count for the simulations, causing successful tests to be reported as failures.

2023-03-18 19:06 UTC, MikeOpenHWGroup requested changes
Please see my comments related to the core_cntrl agent and the tb_exit signal.

2023-03-18 19:06 UTC, MikeOpenHWGroup commented on cva6/tb/uvmt/uvmt_cva6_tb.sv
> +                                                 .tb_exit_o()
Why is `tb_exit_o` added to the RVFI?  This is not a signal related to the RVFI Tracer.

2023-03-18 19:06 UTC, MikeOpenHWGroup commented on cva6/tb/uvmt/uvmt_cva6_tb_ifs.sv
> +                    output logic[31:0] tb_exit_o
Same comment:  tb_exit_o is not a port of the RVFI.

2023-03-18 19:06 UTC, MikeOpenHWGroup commented on cva6/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
> +          (rvfi_vif.tb_exit_o[0]     == 1'b1)
Same comment,.

2023-03-18 19:06 UTC, MikeOpenHWGroup commented on cva6/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
> +   repeat (100) @(posedge env_cntxt.clknrst_cntxt.vif.clk);
If you want this 100-cycle delay to gate the termination of the simulation, it should be placed _before_ dopping the objection.  By dropping its objection a UVM component is signalling to the UVM environment that the simulation can be terminated at any time.

2023-03-20 08:28 UTC, zchamski commented on cva6/tb/uvmt/uvmt_cva6_tb.sv
> +                                                 .tb_exit_o()
This core-v-verif PR has a matching PR on the CVA6 side (https://github.com/openhwgroup/cva6/pull/1125) which replaces the `$finish` calls inside the RVFI tracer with an end-of-test signal forwarded to the TB.

2023-03-20 08:29 UTC, zchamski commented on cva6/tb/uvmt/uvmt_cva6_tb_ifs.sv
> +                    output logic[31:0] tb_exit_o
See above: the corresponding signal was added to the RVFI in https://github.com/openhwgroup/cva6/pull/1125.

2023-03-20 08:58 UTC, zchamski commented on cva6/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
> +          (rvfi_vif.tb_exit_o[0]     == 1'b1)
See above.

2023-03-20 11:59 UTC, MikeOpenHWGroup commented on cva6/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
> +   repeat (100) @(posedge env_cntxt.clknrst_cntxt.vif.clk);
If there needs to be a delay, then it should be before dropping the objection.  Once the objection has been dropped, this component is giving permission to the UVM run-flow to terminate the simulation immediately.  (Note that other components may still have their objections raised, so the simulation may not terminate here.)

2023-03-20 14:31 UTC, zchamski commented on cva6/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
> +          (rvfi_vif.tb_exit_o[0]     == 1'b1)
@MikeOpenHWGroup , alternatively we could think of extending the definition of the `halt` signal in th RVFI interface, but the consequences of this change are unclear at this point.  What's your opinion in this?

2023-03-20 14:50 UTC, MikeOpenHWGroup commented on cva6/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
> +          (rvfi_vif.tb_exit_o[0]     == 1'b1)
The tracer should not signal end-of-test - that is not its purpose.  Rather, the `test-program` should indicate to the testbench that it is ready for the simulation to end.  Both the RISC-V compliance testsuite and the E40 testbenches do that by writing a specific code to a specific address (RISCV compliance calls it `tohost` and the E40 testbenches call it the [virtual peripheral status flags](https://docs.openhwgroup.org/projects/core-v-verif/en/latest/test_programs.html#virtual-peripherals)).

2023-03-20 15:07 UTC, zchamski commented on cva6/tests/uvmt/compliance-tests/uvmt_cva6_firmware_test.sv
> +          (rvfi_vif.tb_exit_o[0]     == 1'b1)
Since the combined core-v-verif PR https://github.com/openhwgroup/core-v-verif/pull/1689  / CVA6 PR https://github.com/openhwgroup/cva6/pull/1075 the tracer tracks the writes to `tohost` performed by test programs, and interprets them in the RISC-V compliance / Spike / RISC-V HTIF way (bit 0 set == end of test, bits [31:1] == test exit code).  Before that, it terminated the simulation upon encountering an ECALL instruction.

Since the tracer is the only observer available in non-UVM settings, so it appears to be the best location to detect the "ready for the simulation to end" condition in a way that is common to all RTL simulations setups.

2023-03-20 15:16 UTC, AyoubJalali commented on cva6/env/uvme/uvma_cva6_core_cntrl_agent.sv
> +      `uvm_warning(log_tag, "fetch toggle not supported in CVA6");
@MikeOpenHWGroup, can't we just replace it with `uvm_info or we can let it empty, because this uvm_error cause problems in the end_of_simulation.

2023-03-21 14:41 UTC, merged