update xsecure hardened PC assertion set
openhwgroup/core-v-verif pull request #1763
Opened 2023-03-29 19:00 UTC by silabs-krdosvik

2023-03-31 13:46 UTC, silabs-mateilga requested changes
Very good PR. Fix copyright year, and this is good to go.

2023-03-31 13:46 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_hardened_pc_assert.sv
> +// Copyright 2022 Silicon Labs, Inc.
Copyright 2023

2023-03-31 13:48 UTC, silabs-mateilga commented
General note to the modularization of the xsecure asserts: At the point of writing, the inevitable removal of the original file is not posted in a PR, don't forget to remove it before wrapping up this work.

2023-04-19 07:31 UTC, silabs-hfegran approved these changes

2023-04-19 07:31 UTC, merged