Adapt the environment and test-bench to execute the AXI agent in active/passive mode
openhwgroup/core-v-verif pull request #1770
Opened 2023-03-30 10:40 UTC by AEzzejjari

This commit allows to us switch the axi_agent mode without changing any part of code.
There is two way to change the agent mode: 

First way: From env_cfg we can change the variable axi_cfg.is_active to UVM_PASSIVE or UVM_ACTIVE.
Second:   From command line by using --axi_active option.

2023-03-31 14:44 UTC, ASintzoff requested changes
I would prefer to have `axi_is_active` instead of `axi_is_passive` (in `cva6.py`) as there is `cfg.axi_cfg.is_active` in System Verilog (principle of least surprise: don't confuse the poor reviewer).

Instead of using 1 and 10 in cva6.py, could you use 1 and 0?

2023-03-31 14:44 UTC, ASintzoff commented on cva6/sim/cva6.py
> +      issrun_opts = "\""+args.issrun_opts+"\""
Lines 938, 941, 943 should be put outside if...else.

2023-03-31 14:44 UTC, ASintzoff commented on cva6/sim/cva6.py
> +                      help="Switch the AXI agent mode. yes for Active, no for Passive")
help="switch AXI agent mode: yes for Active, no for Passive"

2023-03-31 14:44 UTC, ASintzoff commented on cva6/tb/uvmt/cva6_tb_wrapper.sv
> +
Unnecessary blank lines

2023-04-03 00:06 UTC, MikeOpenHWGroup commented
> First way: From env_cfg we can change the variable axi_cfg.is_active to UVM_PASSIVE or UVM_ACTIVE.
> Second: From command line by using --axi_active option.

Neither of these are the "UVM way" of controlling a configuration.  The UVM way is to declare `axi_cfg` as a random variable in the Agent's configuration object.  The UVM testcase can then add constraints to set the value as needed.

2023-04-05 12:10 UTC, AEzzejjari commented
The active vip agent should be the default mode, unless someone needs to revert to the old mode. For this, I implemented a constraint in the base test to set the mode directly. Also, I left the option to change the mode from the command line, as it is easier for someone who doesn't know the environment.

2023-04-06 01:34 UTC, MikeOpenHWGroup commented
> The active vip agent should be the default mode, unless someone needs to revert to the old mode.

Agreed.

> For this, I implemented a constraint in the base test to set the mode directly. Also, I left the option to change the mode from the command line, as it is easier for someone who doesn't know the environment.  

Are you talking about this:
```
 // Variable can be modified from command line, to change the AXI agent mode
   int force_axi_mode = -1;
```

It seems that the variable `force_axi_mode` is simply there to allow for command-line overrides.  This is not "the UVM way".  We can simply this a lot by creating a new testcase that extends the base test.

2023-04-18 21:43 UTC, MikeOpenHWGroup approved these changes

2023-04-18 21:43 UTC, MikeOpenHWGroup commented
OK, as we discussed in the project meeting, I am putting a little bit of water in my wine and approving this PR.

It cannot be merged until the conflict is resolved.

2023-04-19 16:31 UTC, merged