ISACOV : Fixed analysis port & removed isacov unused vif & fixed config knobs
openhwgroup/core-v-verif pull request #1798
Opened 2023-04-12 15:38 UTC by AnouarZajni

- Removed unused interface
- Fixed agent tlm port connection with monitor
- Fixed agent coverage config knobs

2023-04-12 15:38 UTC, AnouarZajni commented
@MikeOpenHWGroup please review

2023-04-13 11:59 UTC, MikeOpenHWGroup requested changes
LGTM  @AnouarZajni.  I have made a couple of comments, but overall this looks good.  As these changes may impact other projects using this agent, I have asked for @silabs-robin to review as well.

2023-04-13 11:59 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_isacov/uvma_isacov_agent.sv
> -  if (!uvm_config_db#(virtual uvma_isacov_if)::get(this, "", "vif", cntxt.vif)) begin
I presume that this is being deleted because the agent does not actually use the VIF; rather it is used by the agent's monitor.  Is that correct?

2023-04-13 11:59 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_isacov/uvma_isacov_agent.sv
> +  uvm_analysis_export#(uvma_rvfi_instr_seq_item_c#(ILEN,XLEN)) rvfi_instr_export;
I like this change (a lot!), but I worry it will have an impact on environments that use this agent.  @silabs-robin can you comment?

2023-04-13 11:59 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_isacov/uvma_isacov_agent.sv
> +      `uvm_error("CFG", "Active mode not yet supported")
AFAIK, the ISACOV agent will never be an active agent.  If I am right, the wording of this message should be stronger: "Misconfiguration error: this agent should not be configured as an active agent".

2023-04-13 13:22 UTC, AnouarZajni commented on lib/uvm_agents/uvma_isacov/uvma_isacov_agent.sv
> +      `uvm_error("CFG", "Active mode not yet supported")
Agree, will update with your message.

2023-04-13 18:32 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_isacov/uvma_isacov_agent.sv
> +      `uvm_error("CFG", "Active mode not yet supported")
Thanks!

2023-04-14 09:31 UTC, silabs-robin approved these changes
Approving based on:
Agreed about removing the pre-rvfi vif.
This PR also fixed a todo so that's nice.
The changes look good.

2023-04-14 09:31 UTC, silabs-robin commented on lib/uvm_agents/uvma_isacov/uvma_isacov_mon.sv
> +  uvm_analysis_imp_rvfi_instr#(uvma_rvfi_instr_seq_item_c#(ILEN,XLEN), uvma_isacov_mon_c) rvfi_instr_imp;
I am fine with this rename. Though I am confused about why the Accellera UVM 1.2 User's Guide seem to prefer the original naming (imp -> export).

![image](https://user-images.githubusercontent.com/75431602/232005995-332644b2-891d-4350-a4a0-17cf9dd14cc5.png)

![image](https://user-images.githubusercontent.com/75431602/232006065-15939ba4-8229-4ecf-92e2-c05e1c8f1ecf.png)

2023-04-14 11:37 UTC, merged

2023-04-14 11:38 UTC, JeanRochCoulon commented
Terrific @AnouarZajni    Very good first contribution !