update xsecure dummy and  assertions
openhwgroup/core-v-verif pull request #1818
Opened 2023-04-18 11:07 UTC by silabs-krdosvik

2023-04-19 08:33 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +    (id_instr[6:0] == OPCODE_OP
General comment: We should consider making a general function set based on the "match_instr.." and "is_.." functions in the rvfi_instr_if, for use with any 32 bit instruction. Code like this would be faster to write, easier to get correct, and easier to read if we did that.

2023-04-19 12:57 UTC, silabs-mateilga requested changes

2023-04-19 12:57 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +  property p_dummy_hint_update_lfsr0(if_dummy_or_hint, lfsr, lfsr_n, write_lfsr_en, write_lfsr_value);
Two unused variables are taken in to this property.

2023-04-19 12:57 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +  property p_dummy_hint_update_lfsr1_lfsr2(if_dummy_or_hint, lfsr, lfsr_n, default_value, lfsr_we, lfsr_w_value);
As LFSR changing in normal operation is very important to the functionality, this assert look a bit to "open ended" to build confidence. Please look at stricter alternatives. Maybe check that if an LFSR is enabled and not written, it has to change?

2023-04-19 12:57 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +    |=>
I think this assert needs to be turned around a bit. As of now it verifies that the lfsr is set to a set of three possibilities, without checking that those possibilities actually change. I would start by changing consequent to only  `lsfr != $past(lfsr)`, and see if you get any legal counterexamples to that assert.

2023-04-24 08:49 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +  property p_dummy_hint_update_lfsr0(if_dummy_or_hint, lfsr, lfsr_n, write_lfsr_en, write_lfsr_value);
Thanks! Will change it in the same manner as for the property below

2023-04-24 08:50 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +  property p_dummy_hint_update_lfsr1_lfsr2(if_dummy_or_hint, lfsr, lfsr_n, default_value, lfsr_we, lfsr_w_value);
Thanks! I guess this is about the same as the comment below? I will use lsfr != $past(lfsr) :-)

2023-04-24 08:50 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +    |=>
Agreed!

2023-04-25 10:50 UTC, silabs-krdosvik commented
I have added everyone for review because I have made a new pkg file with functions as Marton suggested. Since this can become commonly used file I think you should state your opinions, so I can adjust it before it is overly used. 
I am also open to do/structure it in another way, or undo it if that what that seems to be best. @silabs-mateilga , @silabs-hfegran , @silabs-robin , @MikeOpenHWGroup

2023-04-25 11:59 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_functions.sv
> +  //        stored somewhere.
After a few discussions I have reconsidered on this, and I think these should be changed to follow the spec definition of "reading a CSR". This would also apply to the original in rvfi_instr_if. 

I think these changes should be made before committing this new file, I can chip in of you don't have the time.

2023-04-25 12:01 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_functions.sv
I agree with Robin. Also, these are not cv32e40s specific, so the file can be renamed to reflect that. I'd suggest "support_instr_functions", "isa_instr_functions" or a short version of either where we drop the "_instr_".

2023-04-25 12:07 UTC, silabs-mateilga requested changes
Over all good improvements on the previous feedback, and thanks for doing the support functions addition.

2023-04-25 12:43 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_functions.sv
> +  //        stored somewhere.
Or maybe have two functions, one for each case? I can fix it. I think I have put a lot of work on you already, considering all the PRs that needed reviews, hehe :-)

2023-04-25 12:44 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_functions.sv
Aaa, yess!

2023-04-28 06:24 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_functions.sv
> +  //        stored somewhere.
Inside discussion: Marton fixes this (since he must do something similar anyways)

2023-04-28 06:26 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_functions.sv
I have tried to copy the structure other pkg files uses, but you should probably look into how I have done it in case you preferer something else.

2023-04-28 07:18 UTC, silabs-robin commented on lib/support/support_instr_functions.sv
> +`define __UVMT_CV32E40S_INSTR_FUNCTIONS__
This does not match the filename, and it says "40S" while being in "lib/".

2023-04-28 07:18 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_pkg.sv
> +   `include "uvmt_cv32e40s_instr_functions.sv"
Where is this file? Should it be `support_instr_functions.sv`?

2023-04-28 07:18 UTC, silabs-robin commented on lib/support/support_pkgs.sv
> +  `include "support_instr_functions.sv"
Is this file included from multiple places?
I think our compilation might be using a single compilation unit? Not sure. If it does, then one of the includes will probably not include anything.

2023-04-28 15:14 UTC, silabs-robin commented on cv32e40s/fv/dummy_pkg.sv
> +endpackage
Just for everyones information:

Ideally, `dummy_pkg.sv` shouldn't exist.
So, ideally, none of these pkgs should be redefined here.
The only reason they exist is to avoid the non-formal-friendly aspects of the UVM world.

So if this new pkg is 100% formal friendly, it could rather be included via the flists instead of via this dummy pkg.
But if you want, just leave it as it is above and I can take care of fixing it, as I sporadically maintain the core-v-verif formal setup, and nobody is really actively using it anyway.

2023-04-28 18:49 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_pkg.sv
> +   `include "uvmt_cv32e40s_instr_functions.sv"
I have changed it to what we agreed on in our meeting earlier today :-) But to answer: support_instr_functions.sv was a file containing only function, while support_pkgs.sv was a file containing packages (but currentlig only one). Instead of writing the functions into the package, the packet included the file. This structure makes it possible for future packages to also include the same file, therby also containing the functions in the function files. The reason I did this was because it seems like this structure is used for the other packages. 
![image](https://user-images.githubusercontent.com/110398284/235229204-6f3a0cdb-7365-437a-941a-54189037854c.png)
I hope this answers your question.

2023-04-28 18:49 UTC, silabs-krdosvik commented on cv32e40s/fv/dummy_pkg.sv
> +endpackage
Yess!

2023-04-28 18:50 UTC, silabs-krdosvik commented on cv32e40s/fv/dummy_pkg.sv
> +endpackage
Should be good now

2023-04-28 18:56 UTC, silabs-krdosvik commented on cv32e40s/fv/dummy_pkg.sv
> +endpackage
okei, hem, i think i understand. But than I will just remove it for now.

2023-04-28 19:08 UTC, silabs-krdosvik commented on lib/support/support_pkgs.sv
> +  `include "support_instr_functions.sv"
I see. I think this is only included in the place that corresponds to that shown in the comment (given the new structure and name of course).

2023-04-30 20:39 UTC, MikeOpenHWGroup commented on cv32e40s/fv/dummy_pkg.sv
> +endpackage
`support_pkg.sv` in `lib/support` is a good as any name I could come up with.   Years from now someone will hate us for this decision, but they can fix it then.

2023-05-02 06:48 UTC, silabs-krdosvik commented on cv32e40s/fv/dummy_pkg.sv
> +endpackage
Haha, hem, yeah... well well for now then.

2023-05-02 07:59 UTC, silabs-hfegran commented
Thanks for this @silabs-krdosvik, looks good to me

2023-05-02 07:59 UTC, silabs-hfegran approved these changes

2023-05-02 08:00 UTC, merged

2023-05-02 08:27 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_pkg.sv
> +   `include "uvmt_cv32e40s_instr_functions.sv"
> `include "uvmt_cv32e40s_instr_functions.sv"

Can you post a link to the file being included here?

2023-05-02 08:29 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_pkg.sv
> +// Copyright 2023 Silicon Labs, Inc.
Where is this file used?

2023-05-02 08:47 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_instr_pkg.sv
> +// Copyright 2023 Silicon Labs, Inc.
Yess. I have forgot to delete this file, hehe...