update xsecure bus protocol assertions
openhwgroup/core-v-verif pull request #1821
Opened 2023-04-18 13:37 UTC by silabs-krdosvik

2023-04-19 07:45 UTC, silabs-mateilga requested changes

2023-04-19 07:45 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_bus_protocol_hardening_assert.sv
> +  property p_counter(cnt);
This does not verify overflow, but rather underflow. Either change the property or the comment to what is required.

2023-04-19 07:45 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_bus_protocol_hardening_assert.sv
> +  //Verify that the core side and bus side transaction counters in the load store units response fileter dont overflow
spelling mistake, I assume it's response _filter_

2023-04-23 20:40 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_bus_protocol_hardening_assert.sv
> +  property p_counter(cnt);
Good observation! The spec says underflow, so will change the comment.

2023-04-24 10:45 UTC, silabs-mateilga approved these changes
All issues fixed, approving

2023-04-27 09:30 UTC, merged