update xsecure interface integrity
openhwgroup/core-v-verif pull request #1835
Opened 2023-04-23 19:59 UTC by silabs-krdosvik

Try nr.:
1) merged before commented, and must therefore be unmerged
2) branch based un the unmerged commit, didnt work that well
3) made the PR from scratch

2023-04-28 12:51 UTC, silabs-mateilga requested changes

2023-04-28 12:51 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv
> +    || (alert_major_due_to_integrity_err && !rchk_err_instr)
If integrity is disabled, why is it acceptable to have a "alert_major" due to integrity, as long as it isn't an rchk_err ?

2023-05-02 07:09 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv
> +    || (alert_major_due_to_integrity_err && !rchk_err_instr)
The major alert can be set due to numerous reasons. In this assertions we want to check that major alert in not set due to rchk instr error. We therefore check that major alert is not set at all, or that major alert is set, but not due to rchk instr error. I could write a comment on this.

2023-05-02 07:28 UTC, silabs-mateilga commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_interface_integrity_assert.sv
> +    || (alert_major_due_to_integrity_err && !rchk_err_instr)
Sounds good, a comment would be helpful.

2023-05-02 08:05 UTC, silabs-hfegran approved these changes

2023-05-02 08:07 UTC, silabs-hfegran commented
@silabs-krdosvik Looks good, if you can resolve the merge conflicts I can get this merged.

2023-05-02 08:46 UTC, merged