instr_mem_*mask_f and signals to rvfi interface
openhwgroup/core-v-verif pull request #1876
Opened 2023-05-05 12:40 UTC by silabs-krdosvik

This PR adds instr_mem_rmask_f and instr_mem_wmask_f. 
instr_mem_*mask_f returns an array of bits that is similar to rvfi_mem_*mask.
The difference is that when rvfi_mem_*mask is not set due to various reasons, the instr_mem_*mask is set according to what the instruction intended to do.

2023-05-05 12:46 UTC, silabs-mateilga requested changes
Small change required, otherwise it looks good!

2023-05-05 12:46 UTC, silabs-mateilga commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +/*
Commented code should not be PRed without a TODO explaining what it's there for, and preferably when it is to be reinstated. Remove or comment.

2023-05-07 19:47 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_MASK_CMPR          = 32'h 0000_E003;
CMPR = compressed.
![image](https://user-images.githubusercontent.com/110398284/236699454-23ea606a-e58e-4424-8632-033c9aa2460c.png)
If I am not mistaken you mean c.slli and c.lw here? They are both compressed instructions and therefore use the compressed masks.

2023-05-07 19:51 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_MASK_CMPR          = 32'h 0000_E003;
But it is a good point. We have seen that some compressed instructions are not in that format (E003), so maybe I should change the name, but I dont have any good suggutions though.

2023-05-07 20:04 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_MASK_ZC_LOAD_STORE = 32'h 0000_FC03;
Good observation. 
![image](https://user-images.githubusercontent.com/110398284/236700163-606ac417-62a0-4977-a0eb-c5191616b9b9.png)

2023-05-07 20:06 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_OPCODE_CLH   = 32'b 00000000_00000000_100_001_000_1_0_000_00;
true! I guess yes.

2023-05-07 20:07 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  logic                             is_spstore_word_cmp;
Thanks! forgot to remove them

2023-05-07 20:09 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +function logic is_mem_rmask_byte(int mem_txn, int byte_pos);
agreed

2023-05-07 20:09 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +/*
Forgot to remove this...

2023-05-08 09:26 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +function logic is_mem_rmask_byte(int mem_txn, int byte_pos);
but this is an outdated functions, so ill just remove it

2023-05-08 09:27 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  assign csr_addr = rvfi_insn[31:20];
Maybe it will be easier to verify with the new support logic setup from Henrik

2023-05-08 09:28 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_OPCODE_CLH   = 32'b 00000000_00000000_100_001_000_1_0_000_00;
Maybe it will be easier to verify with the new support logic setup from Henrik??

2023-05-10 08:28 UTC, silabs-robin commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_MASK_CMPR          = 32'h 0000_E003;
It is used to extract the **opcode** of **compressed** instructions which have **funct3** in their format?

1. `INSTR_MASK_C_OP_FUNCT3`
2. `INSTR_MASK_COMPRESSED_OPCODE_FUNCT3`
3. `INSTR_MASK_CMPR_OPCODE3`
4. ...

![image](https://github.com/openhwgroup/core-v-verif/assets/75431602/e97cab0b-3953-4da4-84be-edfd37874b11)

2023-05-10 08:30 UTC, silabs-robin commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_MASK_CMPR          = 32'h 0000_E003;
Maybe just `INSTR_MASK_COMPRESSED_FUNCT3` or some variation.

2023-05-10 08:33 UTC, silabs-robin commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> +  localparam INSTR_MASK_ZC_LOAD_STORE = 32'h 0000_FC03;
What was the conclusion?

2023-05-10 08:34 UTC, silabs-robin approved these changes
Approving based on:
There are no major issues outstanding.
The code is a good addition.

2023-05-10 08:48 UTC, silabs-hfegran approved these changes

2023-05-10 08:48 UTC, merged