ISACOV : Add ifdef to avoid VCS compilation error due to unsupported 'with' key word
openhwgroup/core-v-verif pull request #1877
Opened 2023-05-05 13:15 UTC by AyoubJalali

As we discuss, for the CVA6 env we have a vcs compilation error related to the vcs version, the 'with' isn't supported for now, the fix is programmed for July, so to integrate the ISACOV in the CVA6 env, I add ifdef (a final solution after a lot of discuss) as a temporary fix.

2023-05-05 13:38 UTC, silabs-robin requested changes

2023-05-05 13:38 UTC, silabs-robin commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +`ifdef UNSOPPRTED_WITH //ifdef to replace 'with' with 'iff' VCS version don't support 'with' key word
`UNSOPPRTED` seems to be a typo.

2023-05-05 13:38 UTC, silabs-robin commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +    ignore_bins POS_OFF = {POSITIVE} iff (!rs_is_signed);
I am not sure what the `iff` adds here.

Using `with`, the bin would not exist.
Using `iff`, the bin does still exist, and for those instances were it was supposed to not exist, we disallow sampling of it?
Is that the correct interpretation?
If so, then we disallow sampling of something that nevertheless should not exist, so I can't see what the benefit is.

2023-05-05 13:41 UTC, AyoubJalali commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +    ignore_bins POS_OFF = {POSITIVE} iff (!rs_is_signed);
I talking about VCS, because i think the iff work so fine, and effectively works as with

2023-05-05 13:42 UTC, AyoubJalali commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +`ifdef UNSOPPRTED_WITH //ifdef to replace 'with' with 'iff' VCS version don't support 'with' key word
I made ifdef <TAG>
I duplicate all the cover group but with iff instead of with (with cause a compilation error for us)

2023-05-05 13:43 UTC, AyoubJalali commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +`ifdef UNSOPPRTED_WITH //ifdef to replace 'with' with 'iff' VCS version don't support 'with' key word
I think I should modify the TAG

2023-05-06 16:43 UTC, MikeOpenHWGroup requested changes
We need to come up with a solution that does not involve duplicating >1000 lines of code.

2023-05-08 08:19 UTC, silabs-robin commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +`ifdef UNSOPPRTED_WITH //ifdef to replace 'with' with 'iff' VCS version don't support 'with' key word
> We need to come up with a solution that does not involve duplicating >1000 lines of code.

@MikeOpenHWGroup 

> Could the "with/iff"-differentiation be made local to the place where it is used instead

Here is one example:
```
`ifdef WITH_CONSTRUCT_UNSUPPORTED
  `define  WITHIFF  iff
`else
  `define  WITHIFF  with
`endif
```

Her is another:
```
`ifndef  WITH_CONSTRUCT_UNSUPPORTED
  cp_rs_value: coverpoint instr.rs1_value_type {
    ignore_bins POS_OFF = {POSITIVE} iff (!rs_is_signed);
`endif
```

_(NB! I did not check the correctness of the logic nor syntax in those two examples, I just jotted something down.)_

2023-05-08 08:21 UTC, silabs-robin commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +`ifdef UNSOPPRTED_WITH //ifdef to replace 'with' with 'iff' VCS version don't support 'with' key word
NB! Before going with the first option, read my other comments to see what I think of the usage of `iff` here.

2023-05-09 08:07 UTC, AyoubJalali commented
> We need to come up with a solution that does not involve duplicating >1000 lines of code.

I think l'm lazy boy, because i don't want a solution that add **ifdef** in every line **with** is in there, so let's be it, i'll change it

2023-05-09 17:16 UTC, MikeOpenHWGroup commented
I am ready to approve this, but before I do, please have a look at #1881 to see if `iff` gets you what you expect.

2023-05-10 07:07 UTC, silabs-robin requested changes
I must agree that 500 lines of duplicated code is better than 1000 lines of duplicated code.
But preferably there would be 0 lines of duplicated code.
So I would like to know why Mike's suggestion of defining a `WITH` macro can't be used.

--------

In addition, these two comments have not been sufficiently addressed:
https://github.com/openhwgroup/core-v-verif/pull/1877#discussion_r1186105098
https://github.com/openhwgroup/core-v-verif/pull/1877#issuecomment-1540565027

2023-05-10 08:18 UTC, AyoubJalali commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +    ignore_bins POS_OFF = {POSITIVE} iff (!rs_is_signed);
> Using `iff`, the bin does still exist, and for those instances were it was supposed to not exist, we disallow sampling of it?

No for the ignore_bins will ignore them & also for illegal, and actually it's exclude from coverage

2023-05-10 08:24 UTC, AyoubJalali commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +    ignore_bins POS_OFF = {POSITIVE} iff (!rs_is_signed);
![image](https://github.com/openhwgroup/core-v-verif/assets/110232072/5f5e85e0-ace2-4459-9069-4050db4d1b6e)

2023-05-10 09:05 UTC, AyoubJalali commented
@MikeOpenHWGroup @silabs-robin, what mike suggest works after a little change so now there less than 500 lines duplicated

2023-05-10 09:39 UTC, silabs-robin approved these changes
> what mike suggest works after a little change

Excellent! I'm glad it worked. Looks like a nice temporary fix for the VCS problem, and hopefully everyone got what they wanted in the end.

2023-05-11 03:51 UTC, JeanRochCoulon commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +`ifdef UNSUPPORTED_WITH
We can add a TODO or create a github issue to remind it. To me, both can be done, comment can include the github issue reference.

2023-05-11 09:20 UTC, silabs-robin commented on lib/uvm_agents/uvma_isacov/cov/uvma_isacov_cov_model.sv
> +`ifdef UNSUPPORTED_WITH
Either one is fine by me.

_(I have a slight preference for doing it in code, but both options are good.)_

I have given my approval of this PR nonetheless.

2023-05-11 14:43 UTC, merged