ISACOV Agent : Integrate the ISACOV Agent in the CVA6 env
openhwgroup/core-v-verif pull request #1915
Opened 2023-05-17 13:17 UTC by AyoubJalali

2023-05-17 14:44 UTC, MikeOpenHWGroup requested changes
Looks pretty good to me @AyoubJalali.  I have a couple of comments.

2023-05-17 14:44 UTC, MikeOpenHWGroup commented on cva6/env/uvme/uvme_cva6_cfg.sv
> +         cvxif_cfg.cov_model_enabled  == 0;
Why are we disabling the XIF fcov?

2023-05-17 14:44 UTC, MikeOpenHWGroup commented on cva6/env/uvme/uvme_cva6_constants.sv
> +parameter RVFI_NRET = ariane_pkg::NR_COMMIT_PORTS;
We should not be using a package from the RTL in the verification environment.  We should have a package included in `cva6/env/uvme/uvme_cva6_pkg.sv` and use that here.

2023-05-17 14:51 UTC, AyoubJalali commented on cva6/env/uvme/uvme_cva6_cfg.sv
> +         cvxif_cfg.cov_model_enabled  == 0;
Hello,
It's just a decision that i made for now because we don't have a final coverage model for CVXIF (need update), also we wanna see the isacov coverage alone

2023-05-17 21:42 UTC, MikeOpenHWGroup commented on cva6/env/uvme/uvme_cva6_constants.sv
> +parameter RVFI_NRET = ariane_pkg::NR_COMMIT_PORTS;
Of course, you are afraid of this - you _should_ be!

The whole point here is to ensure that the _testbench_, not the _DUT_ is in control of the configuration.  If this is not true, then the DUT is exposed to potential bugs in-which a top-level chip cannot properly configure multiple, heterogeneous CVA6 cores.

So if someone accidentally misconfigured NR_COMMIT_PORTS in the RTL, hopefully we will catch it (when the CI fails).

2023-05-17 21:44 UTC, MikeOpenHWGroup commented on cva6/env/uvme/uvme_cva6_cfg.sv
> +         cvxif_cfg.cov_model_enabled  == 0;
The coverage viewer is hierarchical, so we will always be able to see ISACOV independently.

2023-05-18 08:14 UTC, AyoubJalali commented on cva6/env/uvme/uvme_cva6_constants.sv
> +parameter RVFI_NRET = ariane_pkg::NR_COMMIT_PORTS;
Great, thanks for convincing me

2023-05-18 08:14 UTC, AyoubJalali commented on cva6/env/uvme/uvme_cva6_cfg.sv
> +         cvxif_cfg.cov_model_enabled  == 0;
For this I'll make the change

2023-05-22 07:06 UTC, merged