Cv32e40p/dev baoshan update fp stream tests stage1
openhwgroup/core-v-verif pull request #1930
Opened 2023-05-25 06:25 UTC by dd-baoshan

Update fp stream tests based on requirement from verif plan CV32E40P_F-Zfinx-instructions.xlsx
This is stage1 check in and the development is still on-going. The updates include following
1) fp base stream updates to accommodate more specific scenario testing
2) test yaml updates to include more information on how to exercise f/zfinx tests
3) added new simulation plusargs to prevent overlap of directed streams during instruction placement

note: prerequisite for this PR is PR#1922 (label: cv32e40p)

2023-05-25 11:49 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/cv32e40p_rand_instr_stream.sv
> +/*
It is not a _requirement_, but it would be a good idea to update this header to add the following:
- Copyright 2023 Dolphin Design
- A short description of your modifications.

2023-05-25 11:49 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/custom/riscv_instr_stream.sv
> +/*
It is not a _requirement_, but it would be a good idea to update this header to add the following:
- Copyright 2023 Dolphin Design
- A short description of your modifications.

2023-05-25 14:58 UTC, MikeOpenHWGroup requested changes
This looks good to me @dd-baoshan and it passes a local CI (without ImperasDV).  I've made a couple of comments regarding the license headers.  (Yes, I am being more attentive to this lately.)

2023-05-25 14:58 UTC, MikeOpenHWGroup requested changes
This looks good to me @dd-baoshan and it passes a local CI (without ImperasDV).  I've made a couple of comments regarding the license headers.  (Yes, I am being more attentive to this lately.)

2023-05-26 01:54 UTC, dd-baoshan commented on cv32e40p/env/corev-dv/custom/riscv_instr_stream.sv
> +/*
Thanks for the comments, I have updated the file.

2023-05-26 01:56 UTC, dd-baoshan commented on cv32e40p/env/corev-dv/cv32e40p_rand_instr_stream.sv
> +/*
Thanks for the comments, I have updated the file.

2023-05-26 12:56 UTC, dd-baoshan commented
> This looks good to me @dd-baoshan and it passes a local CI (without ImperasDV). I've made a couple of comments regarding the license headers. (Yes, I am being more attentive to this lately.)

Hi @MikeOpenHWGroup , I have completed the request and pushed the changes. Thanks.

2023-05-26 19:04 UTC, MikeOpenHWGroup approved these changes

2023-05-26 19:04 UTC, merged