[cv32e40p] adding rv32f/zfinx functional coverage based on v2 testplans
openhwgroup/core-v-verif pull request #1990
Opened 2023-06-20 07:17 UTC by dd-vaibhavjain

Adding new functional coverage for RV32F and Zfinx extensions for cv32e40p. This is based on testplans for cv32e40p v2.
We have testplan reviews ongoing and this first version of the functional coverage and can be modified based on review outcomes and coverage analysis.
Functional coverage is for F-multicycle scenarios, operand register corner cases and different cases for various cv32e40p FPU configurations.

2023-06-21 02:12 UTC, MikeOpenHWGroup requested changes
This is a great contribution @dd-vaibhavjain!  A couple of comments:
1. We need to find a way to implement conditional coverage bins without using compiler macros (ifdefs). 
2. It would be **great** to integrate this into `ISACOV`.

2023-06-21 02:12 UTC, MikeOpenHWGroup commented on cv32e40p/env/uvme/cov/uvme_rv32f_covg.sv
> +`ifdef FPU_LAT_0_CYC
Please do _not_ use compiler macros (ifdefs) in the functional coverage model.  We can use parameterization for this.

2023-06-21 10:18 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32f_covg.sv
> +`ifdef FPU_LAT_0_CYC
Thanks @MikeOpenHWGroup for reviewing this. Agreed with your suggestion, that should be the right way to do. Will work to make this covergroup parameterized.

2023-06-21 10:50 UTC, dd-vaibhavjain commented on cv32e40p/env/uvme/cov/uvme_rv32f_covg.sv
> +`ifdef FPU_LAT_0_CYC
Regarding integrating it in ISACOV, I think at the moment this covergroup will not be directly able to integrate there. And would need more work and possibe re-code from scratch. 
Maybe I can take this as an action item for this at the moment. And do this from scratch again for ISACOV ?

2023-08-03 02:28 UTC, dd-vaibhavjain commented
This is currently being re-worked to use ISACOV and incorporate other comments

2023-09-06 12:10 UTC, dd-vaibhavjain commented
Closing this and all comments to be incorporated in a new PR

2023-09-06 12:10 UTC, closed without merging