CVXIF : Fix value of user mode & cus_exc decode
openhwgroup/core-v-verif pull request #2005
Opened 2023-06-23 10:07 UTC by AyoubJalali

2023-06-23 21:50 UTC, MikeOpenHWGroup requested changes

2023-06-23 21:50 UTC, MikeOpenHWGroup commented on cva6/env/uvme/cvxif_vseq/uvme_cvxif_vseq.sv
> +          if (req_item.issue_req.mode == 2'b00 && req_item.issue_req.rs_valid == 2'b11 || req_item.issue_req.rs_valid == 3'b111)
Can we use enumerated types for these `mode` signals?

2023-06-26 13:19 UTC, AyoubJalali commented on cva6/env/uvme/cvxif_vseq/uvme_cvxif_vseq.sv
> +          if (req_item.issue_req.mode == 2'b00 && req_item.issue_req.rs_valid == 2'b11 || req_item.issue_req.rs_valid == 3'b111)
Of course, on it (should I thought about it)

2023-07-05 22:33 UTC, MikeOpenHWGroup approved these changes

2023-07-05 22:34 UTC, MikeOpenHWGroup commented
Thanks @AyoubJalali.  I have approved this PR, but will defer to @JeanRochCoulon or @ASintzoff to merge it in.

2023-07-11 14:47 UTC, merged