first proposal of CV32E40Pv2 ci_check script
openhwgroup/core-v-verif pull request #2016
Opened 2023-06-28 09:19 UTC by XavierAubert

Here is a first proposal for a ci_check script. 

I added all configurations from `cv32e40p/tests/cfg`, and mixed them a bit depending on what it seems to be relevant for me. 

Don't hesitate to tell me if anything's missing/wrong

Some tests are commented because they are not already merged in our working branch (`cv32e40p/dev`) and it will cause the cv_regress to issue a critical error. 

The commands to generate & run the ci_check script will be, for running with vsim and Questa Verification Run Manager with 4 jobs in parallel : 
```shell
./cv_regress --rmdb --file=cv32e40pv2_ci_check.yaml --simulator=vsim --outfile=cv32e40pv2_ci_check.rmdb --lsf "bsub -K -q 'vanilla'" --check_sim_results
vrun -rmdb cv32e40pv2_ci_check.rmdb -run cv32e40p -j 4 -mintimeout 0:300 -nolocalrerun
```

To generate a shell script, the command is : 
```shell
./cv_regress --sh --file=cv32e40pv2_ci_check.yaml --simulator=vsim --outfile=cv32e40pv2_ci_check.sh
```

2023-06-28 10:03 UTC, pascalgouedo requested changes
LGTM

2023-06-28 10:03 UTC, pascalgouedo commented on cv32e40p/regress/cv32e40pv2_ci_check.yaml
> +  uvmt_cv32e40p_pulp_fpu_4cyclat:
4 cycle latency are going to be removed.

2023-06-28 10:03 UTC, pascalgouedo commented on cv32e40p/regress/cv32e40pv2_ci_check.yaml
> +  uvmt_cv32e40p_pulp_fpu_zfinx_4cyclat:
Same

2023-06-28 10:03 UTC, pascalgouedo commented on cv32e40p/regress/cv32e40pv2_ci_check.yaml
> +  uvmt_cv32e40p_pulp_cluster_fpu_4cyclat:
Same

2023-06-28 10:03 UTC, pascalgouedo commented on cv32e40p/regress/cv32e40pv2_ci_check.yaml
> +  uvmt_cv32e40p_pulp_cluster_fpu_zfinx_4cyclat:
Same

2023-06-30 02:36 UTC, dd-vaibhavjain approved these changes

2023-06-30 16:26 UTC, MikeOpenHWGroup commented
LGTM as well.  It seems all the comments were resolved and both @pascalgouedo and @dd-vaibhavjain have approved this PR, so I will merge it in.

2023-06-30 16:26 UTC, merged