[cv32e40p] updates for pulp random streams and new tests
openhwgroup/core-v-verif pull request #2022
Opened 2023-07-04 08:59 UTC by dd-vaibhavjain

This work is continuation of cv32e40p xpulp v2 testplans:
- Update hwloop random test for more improvements and randomization.
- Fix some hwloop stream issues seen in local runs
- add new hwloop isa_stress stream for more randomization
- address some previous fixme/todo for pulp random stream
- Add new random tests for pulp streams - random pulp instructions and mac, simd specific
- Add new regress yaml for pulp random tests

2023-07-05 16:19 UTC, MikeOpenHWGroup reviewed
This looks good @dd-vaibhavjain, however your branch is based on a out-of-date version of the `cv32e40p/dev` branch.  Can you merge in the head (tip) of `cv32e40p/dev`?   Thanks.

2023-07-06 00:54 UTC, dd-vaibhavjain commented
@MikeOpenHWGroup I have just merged the curent cv32e40p/dev head to this branch. Thanks!

2023-07-16 23:11 UTC, MikeOpenHWGroup commented
Hi @dd-vaibhavjain.  I have been looking at this PR until I am cross-eyed and could not see how, but the corev-dv test will not compile.  I had been assuming the problem was at my end since I have recently had #2006 and #2014 merged in.  However, it seems that the trouble is with your fork/branch.  Here are the commands I use:
```
$ git clone -b cv32e40p/dev_vja_hwloop_2 git@github.com:dd-vaibhavjain/core-v-verif.git cv32e40p/dev_vja_hwloop_2
$ cd cv32e40p/dev_vja_hwloop_2/cv32e40p/sim/uvmt
$ make test TEST=hello-world SIMULATOR=vcs USE_ISS=NO
$ make corev-dv CV_CORE=cv32e40p SIMULATOR=vcs; make comp CV_CORE=cv32e40p SIMULATOR=vcs
$ make gen_corev-dv test COREV=YES TEST=corev_rand_jump_stress_test SIMULATOR=vcs USE_ISS=NO
```
All of the above except the last one compile and run as expected.  However the `gen_corev-dv` target fails as below.  I believe (do not know) that there is an excepted ENV variable that is needed to add the copied files to the VCS search path.
```
[mike@aws]$ make gen_corev-dv test COREV=YES TEST=corev_rand_jump_stress_test SIMULATOR=vcs GEN_START_INDEX=0 RUN_INDEX=0 USE_ISS=NO
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:303: CV_SW_CC not defined in either the shell environment, test.yaml or cfg.yaml
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:315: CV_SW_CFLAGS not defined in either the shell environment, test.yaml or cfg.yaml
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:330: RISCV set to /home/mike/corev-openhw-gcc-centos7-20230310
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:331: RISCV_PREFIX set to riscv32-corev-elf-
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:332: RISCV_EXE_PREFIX set to /home/mike/corev-openhw-gcc-centos7-20230310/bin/riscv32-corev-elf-
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:333: RISCV_MARCH set to rv32imc_zicsr_zifencei
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:334: RISCV_CC set to gcc
/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/mk/Common.mk:335: RISCV_CFLAGS set to 
Custom files for riscv-dv generator found here /scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/env/corev-dv/custom. These files will be copied to /scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/vendor_lib/google/riscv-dv/src/ after cloning riscv-dv repo, and will override existing files
*******************************************************************************************
* Generating corev_rand_jump_stress_test with corev-dv...
* with VCS_RUN_FLAGS =   +DISABLE_OVPSIM +ntb_random_seed=1 -assert nopostproc -sv_lib /scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/vendor_lib/verilab/svlib_dpi   
*******************************************************************************************
mkdir -p /scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/sim/uvmt/vcs_results/default/corev-dv/corev_rand_jump_stress_test
for (( idx=0; idx < $((0 + 1)); idx++ )); do \
	mkdir -p /scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/sim/uvmt/vcs_results/default/corev_rand_jump_stress_test/$idx/test_program; \
done
cd  /scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/sim/uvmt/vcs_results/default/corev-dv/corev_rand_jump_stress_test && \
	../simv -licwait 20 -R   +DISABLE_OVPSIM +ntb_random_seed=1 -assert nopostproc -sv_lib /scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/vendor_lib/verilab/svlib_dpi   \
		-l corev_rand_jump_stress_test_0_1.log \
		+start_idx=0 \
		+num_of_tests=1 \
		+UVM_TESTNAME=cv32e40p_instr_base_test \
		+asm_file_name_opts=corev_rand_jump_stress_test \
		+ldgen_cp_test_path=/scratch/mike/GitHubRepos/dd-vaibhavjain/core-v-verif/cv32e40p/dev_vja_hwloop_2/cv32e40p/sim/uvmt/vcs_results/default/corev_rand_jump_stress_test \
		 \
		+instr_cnt=5000 +num_of_sub_program=5 +directed_instr_1=riscv_jal_instr,20
/bin/bash: line 1: ../simv: No such file or directory
make: *** [gen_corev-dv] Error 127
```

2023-07-16 23:57 UTC, dd-vaibhavjain commented
@MikeOpenHWGroup i saw this issue after the PR #2014  merge, and there is a small issue in vcs.mk for gen_corev-dv target which I had fixed it in another open PR  #2029 . We usually untill now didn't run vcs for our internal ci_checks but now we will have to probably include VCS to our ci_check runs.

2023-07-17 00:11 UTC, dd-vaibhavjain commented
For now maybe one way we could try is to merge PR #2029 first and then merge this. That way we should be able to get gen_corev-dv issue fix.

2023-07-17 20:31 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv
> +    cv32e40p_reserved_regs = new[num_of_reserved_regs];
I am not sure if this will work as expected if `num_of_reserved_regs` is a **rand** member because randomization happens _after_ new() is called.

2023-07-17 20:33 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv
> +  int unsigned              num_of_reserved_regs;
This is a static member, but it appears in two constraint blocks (`avail_regs_pulp_instr_c` and `cv32e40p_avail_regs_c`).  This does not compile under VCS S-2021.09.  One way to resolve this issue is to declare `num_of_reserved_regs` to be a rand member.  However, I am not sure that the constructor (`new()`) will work properly if you do that (see my comment on line 149).

2023-07-17 20:34 UTC, MikeOpenHWGroup requested changes
Great suggestion to merge in #2029 before doing this one!   As stated earlier, your logic looks good and I would be ready to approve/merge except there is a compilation error in `cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv`.

2023-07-18 06:00 UTC, dd-vaibhavjain commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv
> +    cv32e40p_reserved_regs = new[num_of_reserved_regs];
Yes this was a bad miss, it should not be rand.
Initially I started off with this member being "rand" entity and added some code but later after some more thought I removed "rand" from here as this does not need to randomized, rather it can just be a fixed set of reserved registers.
But seems like I missed removing the stale code added earlier.
And something to praise VCS here, that it was correctly able to detect incorrect syntax while questa did not complain.

2023-07-18 06:02 UTC, dd-vaibhavjain commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv
> +  int unsigned              num_of_reserved_regs;
Fixed by removing this from constraints as final intention was not to make it a rand member.

2023-07-18 06:03 UTC, dd-vaibhavjain commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_pulp_instr_lib.sv
> +  int unsigned              num_of_reserved_regs;
Fixed in commit f6cf928.

2023-07-20 02:54 UTC, MikeOpenHWGroup approved these changes

2023-07-20 02:54 UTC, MikeOpenHWGroup commented
Latest commit resolves all issues.  Merging...

2023-07-20 02:54 UTC, merged