Expanded disassembler with A extension. Not tested
openhwgroup/core-v-verif pull request #2070
Opened 2023-07-21 11:53 UTC by silabs-inhaahje

2023-07-21 12:27 UTC, silabs-krdosvik commented on lib/support/isa_support.sv
> +    //A
I cant see any immediate flaws, so looks good.

RESOLVED

2023-07-26 09:31 UTC, silabs-hfegran requested changes
Thank you for these updates @silabs-inhaahje, Looks good, I only have a few minor things I think we should consider changing

2023-07-26 09:31 UTC, silabs-hfegran commented on lib/support/isa_support.sv
> +    FUNCT3_A    = 3'b010
I suggest we name this FUNCT3_A_W, as this field refers to the .w (word) in the A-instructions.(i guess it would be easy to add 011 as FUNCT3_A_D as well (double) even though it is not used by us).

2023-07-26 09:31 UTC, silabs-hfegran commented on lib/support/isa_support.sv
> +    FUNCT5_AMOMAXU_W        = 5'b11100
I think we need to split FUNCT5 here, as there are overlapping use-cases between C-extension and A-extension (e.g. funct5_a_something)

2023-07-26 09:31 UTC, silabs-hfegran commented on lib/support/isa_support.sv
> +  } atomic_operand_t;
I think this is fine for now, as the spec is a bit confusing on the syntax of these wrt. assembly.
we could consider making separate instruction names in the future.

2023-07-27 08:58 UTC, silabs-hfegran approved these changes

2023-07-27 08:59 UTC, silabs-hfegran commented
Thanks, looks good now

2023-07-27 08:59 UTC, merged