Merge S->X 2023.08.15 15.01
openhwgroup/core-v-verif pull request #2124
Opened 2023-08-15 13:06 UTC by silabs-robin

This PR merges `cv32e40s/dev` into `cv32e40x/dev`.

No conflicts needed resolving.

Test status:
* ci_check - TODO
* Formal - TODO

2023-08-16 07:15 UTC, silabs-hfegran requested changes

2023-08-16 07:15 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
> +    parameter RAM_ADDR_WIDTH    =  20
Why is this removed from S? (on a merge to X)?

2023-08-16 07:15 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
> -  reg  in_wfi_wfe; // Local model of WFI state of core
Again, this is S, why has this code been removed from S for this merge?
Looks like merge gone wrong in this file - some changes are correct, but some are not

2023-08-16 07:15 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_tb.sv
> +    .RAM_ADDR_WIDTH    (ENV_PARAM_RAM_ADDR_WIDTH)
Why are we missing all the 40S specific parameters here?

2023-08-16 07:15 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +    || id_instr_decoded.rs1.gpr.raw == REGISTER_X0)
perhaps a bit pedantic here, but this could use rs1.gpr.gpr == X0 or rs1.gpr.gpr_abi = ZERO instead of redefining zero to REGISTER_X0

2023-08-16 07:22 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
> +    parameter RAM_ADDR_WIDTH    =  20
> Why is this removed from S?

Here is the PR where it was removed: https://github.com/openhwgroup/core-v-verif/pull/2120

--------

> [...] (on a merge to X)?

The merge takes all changes from `cv32e40s/dev`. The `cv32e40s/` directory is part of core-v-verif for all branches.

2023-08-16 07:29 UTC, silabs-robin commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
> -  reg  in_wfi_wfe; // Local model of WFI state of core
> Looks like merge gone wrong in this file - some changes are correct, but some are not

Looking at the diffs at:
1. https://github.com/openhwgroup/core-v-verif/compare/cv32e40s/dev...silabs-robin:core-v-verif:cvv_xdev_2023.08.15-15.01
2. https://github.com/silabs-robin/core-v-verif/compare/cvv_xdev_2023.08.15-15.01...openhwgroup:core-v-verif:cv32e40s/dev

There is 0 diff, so the file should be identical to the one on cv32e40s/dev.
No conflicts needed resolving on this PR.

2023-08-16 07:33 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_dut_wrap.sv
> +    parameter RAM_ADDR_WIDTH    =  20
https://github.com/silabs-robin/core-v-verif/commit/7e346082084181d75e39479c9271e6e3ec1652d0  I guess this was the commit that change this - I was not aware of this change

2023-08-16 07:34 UTC, silabs-hfegran commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_interrupt_assert.sv
> -  reg  in_wfi_wfe; // Local model of WFI state of core
My bad - I remember this change now

2023-08-16 07:37 UTC, silabs-hfegran approved these changes
LGTM, thanks! The other comments I have should be resolved on the respective branches and not in this merge commmit.

2023-08-17 09:12 UTC, silabs-krdosvik approved these changes
I have ignored the changes in the cv32e40s folder, I have also looked past the wfe stuff. What is remaining is mostly the decoder and support package stuff which looks good. So approving

2023-08-17 09:14 UTC, silabs-krdosvik commented on cv32e40s/tb/uvmt/uvmt_cv32e40s_xsecure_assert/uvmt_cv32e40s_xsecure_dummy_and_hint_assert.sv
> +    || id_instr_decoded.rs1.gpr.raw == REGISTER_X0)
Good point! I will fix it in my upcoming PR! :-) (I think it is nice that you comment on this, because it pushes us to use the decoder in a better manner!)

2023-08-17 10:48 UTC, merged