rework clknrst_if clock and reset init behavior to match async reset strategy
openhwgroup/core-v-verif pull request #214
Opened 2020-09-01 17:41 UTC by strichmo

avoid clock == x overlap with reset assertion
do not ring clocks until a stable reset cycle (1->0->1) is completed

2020-09-03 17:39 UTC, MikeOpenHWGroup requested changes
Hi @strichmo, thanks for doing this, I know it was on my plate...

This PR seems to have a number of updates related to #213 embeded within it.  Can you revert back those files so that this PR only pulls in the clk-and-reset updates?

2020-09-04 12:15 UTC, strichmo commented
Aargh.  The rebase command did not work as I thought.  I should've checked that.  Let me just rebase this up to the current master.

2020-09-04 12:30 UTC, strichmo commented
Force pushed the rebased branch onto current master.

2020-09-04 16:31 UTC, MikeOpenHWGroup approved these changes

2020-09-04 16:31 UTC, merged