rename to follow name convention
openhwgroup/core-v-verif pull request #2198
Opened 2023-09-13 11:39 UTC by silabs-krdosvik

Follow naming convention.

I dont think this will pass formal or ci check without the upcomming changes on cv32e40x-dv.

2023-09-13 11:58 UTC, silabs-robin requested changes
Blocking based on:
_"I dont think this will pass formal or ci check without the upcomming changes on cv32e40x-dv."_.
We had decided that `cv32e40x/dev` should always be clean.

2023-09-14 07:43 UTC, silabs-robin commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
https://github.com/openhwgroup/cv32e40x-dv/pull/39#discussion_r1325451715

2023-09-28 07:28 UTC, silabs-robin commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
> I dont think this will pass formal or ci check without the upcomming changes on cv32e40x-dv.

_"the upcomming changes on cv32e40x-dv"_ refers to https://github.com/openhwgroup/cv32e40x-dv/pull/39 , right?

That one is merged now, but it will have zero effect here until the hash is updated too.

2023-09-28 14:06 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
Correct. Latest commit fix this.

2023-09-28 14:40 UTC, silabs-krdosvik commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
NM! What is needed is an update of the hash in the cv32e40x-dv repo: https://github.com/openhwgroup/cv32e40x-dv/pull/48. The cv32e40x-dv PR can be merged after this is merged. But should be merged pretty quickly afterwards.

2023-09-28 14:48 UTC, silabs-robin commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_instr_if.sv
The hash could be updated from this PR.
But I can also just quickly merge both in succession.
Am I guaranteed that ci_check passes after merging both?

2023-10-02 12:51 UTC, silabs-krdosvik commented
Now, https://github.com/openhwgroup/cv32e40x-dv/pull/48 is merged. This can than be merged.

2023-10-02 12:57 UTC, silabs-robin commented on bin/clonetb
Is ci_check passing and formal working now that all other PRs are merged and the hash to x-dv is updated?

2023-10-02 14:16 UTC, silabs-krdosvik commented on bin/clonetb
Everything listed ^, seems to work fine, except clic test on ci check

2023-10-02 14:20 UTC, silabs-robin commented on bin/clonetb
Awesome. Thanks.

2023-10-02 14:21 UTC, silabs-robin approved these changes
Approving based on:
All conversations resolved.
Test status reportedly ok.

2023-10-02 14:21 UTC, merged