[Xcelium support] Bugfix uvm sysverilog compliant
openhwgroup/core-v-verif pull request #2365
Opened 2024-02-13 16:18 UTC by CoralieAllioux

Those minor fixes are suggested in the context of supporting Cadence Xcelium simulator for cva6 verification.
Those modifications allows Xcelium to compile and does not impact VCS usage.

This has been check with VCS 2021.09.

2024-02-14 08:50 UTC, CoralieAllioux commented
Hi @MikeOpenHWGroup , the ECA for Isabelle is now solved for this PR

2024-02-21 09:20 UTC, MarioOpenHWGroup requested changes
Besides the commented function, LGTM!

2024-02-21 09:20 UTC, MarioOpenHWGroup commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_agent.sv
> +   //extern function void connect_reference_model();
Instead of commenting it, you can remove it as it is not implemented nor used anywhere

2024-02-21 09:35 UTC, CoralieAllioux commented on lib/uvm_agents/uvma_rvfi/uvma_rvfi_agent.sv
> +   //extern function void connect_reference_model();
This is done, thank you for the comment

2024-02-21 10:07 UTC, merged