Coverage analysis update and new regress features for shell script generation
openhwgroup/core-v-verif pull request #2380
Opened 2024-02-27 15:32 UTC by XavierAubert

This time, the PR will be a short one to describe. 

During the previous week, @dd-baoshan main effort was on coverage exclusion files : 
- XavierAubert#165
- XavierAubert#166
- XavierAubert#169
And also on improving coverage holes (XavierAubert#168 & XavierAubert#170)

This PR also contains an update to shell script generation of cv_regress script to allow for multiple test_cfgs to be run (see XavierAubert#167). There was not so much to add since most of the modifications I introduced for rmdb generation were just to be able to run regressions using vrun... 

I also added a readme file inside `cv32e40p/regress` to explain how we generate regressions for v2 inside our environment using cv_regress. Tell me if it seems clear enough for you @MikeOpenHWGroup

2024-02-27 18:00 UTC, MikeOpenHWGroup requested changes
Looks (mostly) good to me @XavierAubert.  A couple of minor comments.  I made a comment in `cv32e40p/env/corev-dv/instr_lib/cv32e40p_instr_for_func_cvg_lib.sv` about multiple class definitions in one file.

2024-02-27 18:00 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_instr_for_func_cvg_lib.sv
> +class cv32e40p_xpulp_single_hwloop_stream_directed extends cv32e40p_xpulp_hwloop_base_stream;
Maybe I have missed this in the past, but I would rather have one-and-only-one SV class per file.   Please move this to a seperate file.  It may even make sense to create a new directory for directed streams such as `cv32e40p/env/corev-dv/instr_lib/directed_streams` or `cv32e40p/env/corev-dv/directed_streams`.

2024-02-27 18:00 UTC, MikeOpenHWGroup commented on cv32e40p/env/uvme/cov/uvme_debug_covg.sv
> +        irq_dreq_trig_ill : cross dreq, irq, trigger, ill; // irq + haltreq + trigger (illegal)
Thanks for the comments!

2024-02-27 18:00 UTC, MikeOpenHWGroup commented on cv32e40p/env/uvme/cov/uvme_debug_covg.sv
> +        cr_dbg_irq_while_multi_cyc_f_A : cross cp_apu_req_valid, cp_apu_grant_valid, cp_dbg_req, cp_irq {
Impressive!  Does this cross appear in a DV plan?

2024-02-27 18:00 UTC, MikeOpenHWGroup commented on cv32e40p/sim/tools/vsim/exclusion/README
> +This directory contains waiver files for cv32e40p v2 verification.
If this file is named `README.md`, then GitHub will automatically render it into html when you view it with your browser.  (Obviously, this is just FYI - no need to gate the merge on this trivial item.)

2024-02-27 18:00 UTC, MikeOpenHWGroup commented on cv32e40p/tests/uvmt/compliance-tests/uvmt_cv32e40p_firmware_test.sv
> +   if ($test$plusargs("gen_random_debug") || $test$plusargs("gen_reduced_rand_dbg_req")) begin
In my past work-lives I have typically added these controls using a UVM testcases.  However, CORE-V-VERIF has evolved to have a single testcase (this one) with many plusargs controlled by yaml files and scriptware.

Which do you prefer?

2024-02-27 18:00 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_float_instr_lib.sv
> +  virtual function void insert_illegal_instr();
AFAICT, this function does not create illegal instructions.  The comment says `create a placeholder`, does this mean you intend to update this function in the future?  If so a "TODO" in the comment would be useful.

2024-02-28 00:57 UTC, dd-baoshan commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_instr_for_func_cvg_lib.sv
> +class cv32e40p_xpulp_single_hwloop_stream_directed extends cv32e40p_xpulp_hwloop_base_stream;
Currently, every file contains multiple classes. e.g a base class and its extension classes such as pulp related classes (cv32e40p_pulp_instr_lib.sv), fpu related classes (cv32e40p_float_instr_lib.sv) and hwloop related classes (cv32e40p_pulp_hwloop_instr_lib.sv). 
The recomendation to have one class per file was not aware since begining of test development. 

as for cv32e40p_instr_for_func_cvg_lib.sv, it is use to keep all the new classes that constraint/directed in the way to improve the missing functional coverage.

2024-02-28 00:59 UTC, dd-baoshan commented on cv32e40p/env/uvme/cov/uvme_debug_covg.sv
> +        cr_dbg_irq_while_multi_cyc_f_A : cross cp_apu_req_valid, cp_apu_grant_valid, cp_dbg_req, cp_irq {
I do not think they appear in the DV plan. They were created by previous owner during v2 and I just refine them. @XavierAubert , could you please further cross check on this.

2024-02-28 01:02 UTC, dd-baoshan commented on cv32e40p/tests/uvmt/compliance-tests/uvmt_cv32e40p_firmware_test.sv
> +   if ($test$plusargs("gen_random_debug") || $test$plusargs("gen_reduced_rand_dbg_req")) begin
testcase (yaml file) with plusargs seems to be wasier to maintain. Also, there is a flow improvement in v2 which introduce test_cfg option to include plusargs that enable certain features in test environment.

2024-02-28 01:22 UTC, dd-baoshan commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_float_instr_lib.sv
> +  virtual function void insert_illegal_instr();
we have riscv_illegal_instr which generate a random illegal instruction based on configuration and return it as string.
Directed stream instruction is to generate a stream of valid riscv_instr which keep in the instr_list. 

In order to slot the illegal instruction in directed stream, I use following workaround (I could not find any example or way in existing stream).
1) create a valid riscv_instr (it is just a placeholder to allocate a place for illegal instruction insertion)
2) set the helper field "is_illegal_instr" on this valid riscv_instr for post processing of directed stream in sequence
3) in sequence below, it it detected any is_illegal_instr==1 in valid riscv_instr, it will be dropped and replace with illegal instruction from riscv_illegal_instr. (see below image)

![image](https://github.com/openhwgroup/core-v-verif/assets/131629054/4f8848ea-6ef7-4835-8661-fe70b34f45d3)

2024-02-28 14:33 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_instr_for_func_cvg_lib.sv
> +class cv32e40p_xpulp_single_hwloop_stream_directed extends cv32e40p_xpulp_hwloop_base_stream;
OK.  I just re-checked our [coding style guidlines](https://github.com/openhwgroup/core-v-verif/blob/master/docs/CodingStyleGuidelines.md), and saw this:
```
1.4.1. Recommended: All files shall contain one and only one class, interface, package, or module.
Cases where items are very small and can be neatly grouped together may be placed in the same
file (for example, sequence libraries).
```
So it seems that although it is _recommended_ to have one-and-only-one SV class per file, what we have now is compliant with the guidelines.

2024-02-28 14:44 UTC, MikeOpenHWGroup commented on cv32e40p/env/uvme/cov/uvme_debug_covg.sv
> +        cr_dbg_irq_while_multi_cyc_f_A : cross cp_apu_req_valid, cp_apu_grant_valid, cp_dbg_req, cp_irq {
OK.  I am worried about adding a lot of coverage bins that are not part of the DV plan, but do not want to delay this PR.  So I will resolve this conversation and have opened #2381 to discuss it further.

2024-02-28 14:52 UTC, MikeOpenHWGroup commented on cv32e40p/env/corev-dv/instr_lib/cv32e40p_float_instr_lib.sv
> +  virtual function void insert_illegal_instr();
Got it.  It would be helpful to document this somewhere, so I have created #2382 to track that.

2024-02-28 14:55 UTC, MikeOpenHWGroup approved these changes
I've created two issues related to this PR, but their resolution does not need to gate the merge.  Approving & merging.

2024-02-28 14:56 UTC, merged