Changes to reply to issue #2403, #2407 and #2408
openhwgroup/core-v-verif pull request #2409
Opened 2024-04-12 09:14 UTC by ludovicpion

To fix or provide changes related to #2403, #2407 and #2408

2024-04-12 14:32 UTC, MikeOpenHWGroup requested changes
Thanks for this @ludovicpion.  I would like to request a few changes:
1. There are separate copies of the LICENSE file for the `pulse_gen` and `bp_gen` components.  These are not necessary since there is a top-level LICENSE file for this repository and there are license headers for all svh files.
2. The `bp_gen` has an added layer of heirarchy (`bp_gen/bp_gen`) that does not seem to have any purpose.

2024-04-15 07:59 UTC, ludovicpion commented
Hi @MikeOpenHWGroup,

Regarding  layer of heirarchy for the bp_gen, it is a mistake. I just fixed it.

For the LICENSE, all the cv_dv_utils have the same of managing it. I know that there is some redudancy but we agreed at the begining that it was ok to keep it like this. Is there any problem now?

Thanks,
Ludovic

2024-04-15 12:20 UTC, MikeOpenHWGroup approved these changes

2024-04-15 12:23 UTC, MikeOpenHWGroup commented
Thanks for fixing the "extra layer of hierarchy" issue.  The redundant license files are unnecessary, but I am unaware of any legal reason not to included them, so I will approve/merge this PR.

Thanks for the contribution to CORE-V-VERIF!

2024-04-15 12:23 UTC, merged