Few enhancements on cv_dv_utils
openhwgroup/core-v-verif pull request #2475
Opened 2024-06-20 11:14 UTC by ludovicpion

[cv_dv_utils generic_agent] by default it is an active agent now
[cv_dv_utils tp_trans] added a python script to create OHG verification TestPlan
[cv_dv_utils bp] added force and release task

2024-07-15 08:15 UTC, ludovicpion commented
Is there any problem with this pull-request which prevent it to be accepted?

2024-07-16 15:02 UTC, MikeOpenHWGroup requested changes
Looks good to me @ludovicpion, thanks.  Please add an SPDX license header to `tp_translator.py`.  Note that it doesn't need to be anything more than a two or three liner.

2024-07-17 07:30 UTC, ludovicpion commented on lib/cv_dv_utils/python/tp_translator/tp_translator.py
> +import pandas as pd
Changes done

Thanks

2024-07-17 13:06 UTC, MikeOpenHWGroup approved these changes

2024-07-17 13:06 UTC, merged