Debug coverage and assertions
openhwgroup/core-v-verif pull request #249
Opened 2020-09-22 16:24 UTC by silabs-oysteink

2020-09-22 19:59 UTC, MikeOpenHWGroup reviewed
This all looks good @silabs-oysteink.  There are a few items I am going to ask @strichmo to review before approving.

2020-09-23 03:11 UTC, strichmo requested changes
@silabs-oysteink @MikeOpenHWGroup A general request for this PR.  Even though SystemVerilog allows covergroups in modules we'd prefer to have the covergroups in the class-based world.  This enables common coverage control, instance naming and some other standardization.  

This does require some overhead.

The debug covergroups could be placed in a class similar to how it is done in:
cv32/env/uvme_cv32/cov/uvme_interrupt_covg.sv

The other complication is that you will need an interface to get the "signals" from the design into the class/covergroups.  That would require an interface definition connected to the signals you need (in assert module).  Then you could simply add that to the uvma_debug_cntxt_c as a virtual interface.  You can then configure the new debug covergroup class with the cntxt handle of the cv32 as the interrupt_covg does.

Please let me know if I can help plumb this into your PR if something is confusing.

2020-09-24 12:31 UTC, strichmo approved these changes
Thanks @silabs-oysteink !  Looks good to me.  @MikeOpenHWGroup should be ready for test and merge.

2020-09-25 11:19 UTC, MikeOpenHWGroup commented on cv32/tb/uvmt_cv32/uvmt_cv32_tb_ifs.sv
> +    input logic [11:0] csr_addr
There is a missing comma at the end of this line.  I'll fix it.

2020-09-25 11:20 UTC, MikeOpenHWGroup approved these changes

2020-09-25 11:20 UTC, merged