Fix issue #2479 #2468
openhwgroup/core-v-verif pull request #2490
Opened 2024-07-02 12:06 UTC by AyoubJalali

This MR fix issues cvv #2479 & #2468

2024-07-02 13:44 UTC, AyoubJalali commented
I did some modification to fix some issues, can you review it @MarioOpenHWGroup , thanks !!

2024-07-03 08:14 UTC, MarioOpenHWGroup requested changes
I think in overall looks nice but I think the addition of the "h" extension should be in the rvfi_spike.sv in the `libs/uvm_components/uvmc_reference_model/`

2024-07-03 11:37 UTC, AyoubJalali commented
@MarioOpenHWGroup can you look again

2024-07-03 13:54 UTC, MarioOpenHWGroup approved these changes

2024-07-03 13:59 UTC, merged