Riviera-PRO support
openhwgroup/core-v-verif pull request #269
Opened 2020-10-02 06:54 UTC by dawidzim

Hey!
This is a patch which added support for Riviera-PRO simulator

2020-10-14 13:33 UTC, MikeOpenHWGroup commented on lib/uvm_libs/uvml_logs/uvml_logs_constants.sv
> +`ifdef _VCP
Hi @dawidzim, this looks like it will work, but I am not certain for the need or its purpose, can you comment?

2020-10-14 13:40 UTC, MikeOpenHWGroup requested changes
Hi @dawidzim, this all looks very good.  Before I merge it in:
- I will regress it on our MetricCI platform.  I expect no issues and will have results in less than an hour.
- I have added for the addition of an SPDX header to `riviera.mk`.  See my comment.

2020-10-14 13:40 UTC, MikeOpenHWGroup commented on cv32/sim/uvmt_cv32/riviera.mk
> +#
Please add the following SPDX header at this location:
```
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.0
```
This is a new requirement we have been asked to add to all headers to enable script-based audits of our code base.

2020-10-15 07:16 UTC, dawidzim commented
Hey @MikeOpenHWGroup 
In new commit I added:
-SPDX header
-`riviera` for `riscv-dv`

I also want to remind you about pullrequest #220

2020-10-15 10:32 UTC, MikeOpenHWGroup approved these changes

2020-10-15 10:32 UTC, merged