Use state machine in step & compare instead of asynchronous always blocks
openhwgroup/core-v-verif pull request #355
Opened 2020-11-10 17:26 UTC by GTumbush

Updated uvmt_cv32_step_compare.sv to use a state machine instead of asynchronous always blocks.  Passes ci_check in lee_moore branch that runs interrupt_test, corev_rand_interrupt_0, and corev_rand_interrupt_1. All pass.

Note, this file was cherry picked from https://github.com/GTumbush/core-v-verif/tree/lee_moore hash 12b6874 with log "Move stop/start_clk to state machine".  It does not contain Lee's latest modifications to this file.  It does not solve issues https://github.com/openhwgroup/cv32e40p/issues/549 and https://github.com/openhwgroup/cv32e40p/issues/548.  Since these issues do not gate RTL freeze I want to get this upgrade in master ASAP.

2020-11-10 17:55 UTC, MikeOpenHWGroup requested changes
Hi @GTumbush, it looks like you've got some new updates mixed in with some old ones.  Can you resubmit with the updates to everything in `vendor_lib` excluded?

2020-11-10 17:55 UTC, MikeOpenHWGroup commented on vendor_lib/google/corev-dv/corev_asm_program_gen.sv
> -    if (cfg.gen_debug_section) begin
Why is this change here?   It seems completely unrelated to this PR and removes stable code that's been there for almost two weeks.

2020-11-10 17:55 UTC, MikeOpenHWGroup commented on vendor_lib/google/corev-dv/corev_asm_program_gen.sv
> +    instr_stream.push_back($sformatf("                  lui %s,print_port>>12", td_nam[0].tolower()));
This is already in place.  I'm thinking you've got some out-of-date files.

2020-11-10 17:55 UTC, MikeOpenHWGroup commented on vendor_lib/google/corev-dv/corev_asm_program_gen.sv
> +  // ECALL trap handler - corev-dv does not use the ecall to signal test_done as standard riscv-dv does.
Same comment.

2020-11-10 17:55 UTC, MikeOpenHWGroup commented on vendor_lib/imperas/riscv_CV32E40P_OVPsim/README.md
> +Date   : 20201104
This file is very out of date.

2020-11-10 17:55 UTC, MikeOpenHWGroup commented on vendor_lib/imperas/riscv_CV32E40P_OVPsim/sv/riscv_CV32E40P.sv
> +    export "DPI-C" task     setDISCARD;
Out of date.

2020-11-10 21:13 UTC, GTumbush commented
This was my attempt to cherry pick uvmt_cv32_step_compare.sv. Should I be making a pull request to core-v-verif/master or core-v-verif/lee_moore?

2020-11-11 00:19 UTC, MikeOpenHWGroup commented
pull request to core-v-verif/maste

2020-11-11 16:11 UTC, GTumbush commented
Hi Mike, do you have 5min to help me with this in a meeting? If I do a pull request to core-v-verif/lee_moore I see one file changed,  uvmt_cv32_step_compare.sv  

If I do a pull request to core-v-verif/master I see 3 files changed:
1) uvmt_cv32_step_compare.sv which makes sense, this is the change I want to push 
2) cv32_ci_check.yaml which makes sense since it is only changed in lee_moore
3) corev_asm_program_gen.sv which makes no sense since the file in my branch is the same as in core-v-verif/master

Thanks,
Greg

2020-11-11 16:14 UTC, MikeOpenHWGroup commented
Sure.  I'm unavailable until 12:00PM EST and then after 1PM.

2020-11-11 23:52 UTC, MikeOpenHWGroup commented
Closing is PR as it is made unnecessary by #359

2020-11-11 23:52 UTC, closed without merging