fix jalr_cg, was missing the zero bin
openhwgroup/core-v-verif pull request #370
Opened 2020-11-13 23:25 UTC by strichmo

was also computing imm as pc-relative but this was not correct

Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>

2020-11-13 23:39 UTC, MikeOpenHWGroup commented on cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
> +        cp_offset: coverpoint get_imm(ins.ops[1].val, "jalr") {
Good catch!   Pretty sure this was my bad.

2020-11-13 23:44 UTC, MikeOpenHWGroup requested changes
Couple of questions about this one - see my review comments.

2020-11-13 23:44 UTC, MikeOpenHWGroup commented on cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
>              bins pos  = {[1:$]};
Yes, but don't we want to cover HINTs?

2020-11-13 23:44 UTC, MikeOpenHWGroup commented on cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
> +                    // Usually the Decoder from ISS presents all three operands such as R1:s6 C:785 R2:s6
How do you know this?

2020-11-15 16:40 UTC, strichmo commented on cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
> +                    // Usually the Decoder from ISS presents all three operands such as R1:s6 C:785 R2:s6
Examined lots of logs.  Ideally we would put asserts on the output of 3rd party ISS we don't have direct control of stimulus, but I can't say that is worth the effort to implement.  Yet another reason we should be pulling our functional coverage from our own monitor/tracer so we can append appropriate assertion code.

2020-11-15 16:42 UTC, strichmo commented on cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
>              bins pos  = {[1:$]};
For all of the standard (RV32I) hints we get coverage through bins in the standard ISA instructions.  (Hints in RV32I are a set of computational instructions with rd=x0).

For RV32C I just added the zero register to appropriate C instructions that may encode hints so we will get coverage.

I also added hint ratio into the rand_instr and rand_instr illegal tests to generate these hints.

2020-11-15 17:05 UTC, MikeOpenHWGroup commented on cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
> +                    // Usually the Decoder from ISS presents all three operands such as R1:s6 C:785 R2:s6
> Yet another reason we should be pulling our functional coverage from our own monitor/tracer so we can append appropriate assertion code.

Absolutely agreed!

2020-11-15 17:16 UTC, strichmo commented
I force-pushed an updated branch, rebased to master to alleviate merging issues.

2020-11-15 17:43 UTC, MikeOpenHWGroup commented on cv32/env/uvme_cv32/cov/uvme_rv32isa_covg.sv
>              bins pos  = {[1:$]};
I understand and agree with your first two points.   However, I do not see why the immediate value in `c.slli rd, uimm` cannot be zero for non-hint instructions.  Of course,  `c.slli x8 0` won't actually _do_ anything, but isn't that the point?

In the interests of moving forward quickly, I'll approve/merge this PR and open an issue.

2020-11-15 17:45 UTC, MikeOpenHWGroup approved these changes

2020-11-15 17:45 UTC, merged