add wfis directly to compressed lw sw stream to enhance coverage
openhwgroup/core-v-verif pull request #393
Opened 2020-11-19 18:29 UTC by strichmo

Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>

2020-11-19 21:08 UTC, MikeOpenHWGroup requested changes
Couple of comments/questions.

2020-11-19 21:08 UTC, MikeOpenHWGroup commented on vendor_lib/google/corev-dv/corev_load_store_instr_lib.sv
> +  function void post_randomize();
Generally I recommend having a one-to-one mapping of classes to files.

2020-11-19 21:08 UTC, MikeOpenHWGroup commented on formal/tests/cv32e40p_formal_tb.sv
> +// Copyright 2020 Silicon Labs, Inc.
Wow!   This one caught me off guard.   Not against it (far from it), but it doesn't seem to fix with this particular pull-request.   Also, we ought to make this part of an overall formal strategy.

2020-11-19 23:09 UTC, strichmo commented on formal/tests/cv32e40p_formal_tb.sv
> +// Copyright 2020 Silicon Labs, Inc.
Oh yikes!  That never should've gone in.  That's our local stuff...sorry!!!!  I will pull it out of the PR.

2020-11-19 23:12 UTC, strichmo commented on vendor_lib/google/corev-dv/corev_load_store_instr_lib.sv
> +  function void post_randomize();
I go back and forth on whether sequence "libraries" should be multiple classes per file or one-per.  I think what generally works best is to create a new directory for sequences and go one class per file.  How do you feel about making that change with the current corev-dv sequences?

There's only 6 class definitions to refactor.

2020-11-19 23:53 UTC, strichmo commented on vendor_lib/google/corev-dv/corev_load_store_instr_lib.sv
> +  function void post_randomize();
I went ahead and made the change to break out corev-dv directed streams into their own class files (and their own directory).

2020-11-20 00:51 UTC, MikeOpenHWGroup approved these changes

2020-11-20 00:52 UTC, merged