Removed magic numbers for mm_ram addresses and added a cycle counter
openhwgroup/core-v-verif pull request #510
Opened 2021-03-08 10:18 UTC by silabs-mateilga

Signed-off-by: Marton Teilgard <mateilga@silabs.com>

The magic numbers used to signify the mm_ram addresses have been made in to parameters for readability.

A cycle counter has been added to mm_ram. The motivation for this is to enable benchmarks running on the core to access and record the cycle count for a given testcase, which will be necessary for implementing EMBench and Coremark in core-v-verif.

This PR is relevant to issues #494 and #495.

2021-03-08 14:45 UTC, MikeOpenHWGroup requested changes
Love it!   Thanks @silabs-mateilga for the search-and-destroy of those magic numbers.   You have done a great service to the core-v-verif community.

I wonder if the mm_ram is the best place for the cycle counter.  This might not be the most obvious location and if the mm_ram is replaced, the cycle counter could disappear and the benchmarks will be impacted.  It seems to be that this could be  a feature of the testbench itself, or even a component of the testbench.

2021-03-08 15:23 UTC, strichmo commented
For now, the Virtual Peripheral in mm_ram is the best place we have to enable tests (in C or assembly) to control the testbench.  Even if we had a proper UVM-agent peripheral, I would argue that it makes sense, especially in a benchmark context, to support this functionality.  This would include the other VP features in the mm_ram.

Once we take on the creation of a UVM agent proper, I would argue for the porting of VP features one-for-one in the new peripheral.

2021-03-08 15:45 UTC, MikeOpenHWGroup approved these changes
Ah, I missed the part where the cycle count is actually readable and reset-able.  In that case, I agree that mm_ram is (currently) the proper place for this to be.  @silabs-mateilga, I'll update the virtual peripheral documentation for that and ask you to review it.

Speaking of things I missed the first time, I've made a comment about the use of $fatal().  @silabs-mateilga, please address that and I'll approve this PR.   Thanks!

2021-03-08 15:45 UTC, MikeOpenHWGroup commented on cv32e40p/tb/core/mm_ram.sv
> +                $fatal(1, "cycle counter read after overflow");
Please replace the call to $fatal() with an invocation of the \`uvm_fatal() macro.  (Yes, I _know_ some historical code still uses $fatal(), but we should not add new ones.)

2021-03-08 15:48 UTC, strichmo commented on cv32e40p/tb/core/mm_ram.sv
> +                $fatal(1, "cycle counter read after overflow");
@MikeOpenHWGroup This one might be my fault.  I steered them to $fatal as I thought this code has to run under Verilator??

2021-03-08 16:05 UTC, MikeOpenHWGroup commented on cv32e40p/tb/core/mm_ram.sv
> +                $fatal(1, "cycle counter read after overflow");
Yeah, we need a definitive statement on how we support Verilator.   That's on me.  For now, please use the uvm messaging service (\`uvm_fatal(), \`uvm_error(), \`uvm_info(), etc.) and I'll make the appropriate fixes/hacks after the fact to keep Verilator going.

2021-03-08 16:57 UTC, silabs-mateilga commented on cv32e40p/tb/core/mm_ram.sv
> +                $fatal(1, "cycle counter read after overflow");
Thanks for the input! I'll change the call to the uvm macro, expect an update tomorrow.

2021-03-08 17:11 UTC, MikeOpenHWGroup commented on cv32e40p/tb/core/mm_ram.sv
> +                $fatal(1, "cycle counter read after overflow");
:+1:

2021-03-09 09:58 UTC, silabs-mateilga commented on cv32e40p/tb/core/mm_ram.sv
> +                $fatal(1, "cycle counter read after overflow");
Fix is in. I also took it one step further and updated other $fatal calls in the file, and parameterized the info tag for the uvm messaging calls.

2021-03-09 13:12 UTC, MikeOpenHWGroup approved these changes

2021-03-09 13:12 UTC, merged