add in support for IO memory updating the RM memeory view
openhwgroup/core-v-verif pull request #580
Opened 2021-04-30 11:12 UTC by eroom1966

This pull Request includes the feedback of IO updates for the virtual peripherals so that the RM sees the same values read from IO as the RTL

2021-04-30 16:35 UTC, MikeOpenHWGroup commented on cv32e40p/tb/core/mm_ram.sv
> +            uvmt_cv32e40p_tb.iss_wrap.ram.RND_STALL = data_rdata_mux;
Why does the `iss_wrap.ram` need to know about stalls?

2021-04-30 16:35 UTC, MikeOpenHWGroup commented on cv32e40p/tb/core/mm_ram.sv
> +            uvmt_cv32e40p_tb.iss_wrap.ram.RND_NUM = data_rdata_mux;
Dito.

2021-04-30 16:46 UTC, MikeOpenHWGroup requested changes
Hi @eroom1966, I've added a couple of comments/questions to `mm_ram` and requested a small change to `step_compare`.

Looking at the changes to `imperas/design/ram.sv`, I will reiterate my comments from the meeting.  It looks to me like we are replicating the virtual peripherals from the core's memory in the RM's memory.   This creates a significant maintenance headache, especially with all the "magic numbers" that have to be kept aligned.

I'll comment on this further in our email thread.

2021-04-30 16:46 UTC, MikeOpenHWGroup commented on cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv
> +    always @(posedge uvmt_cv32e40p_tb.dut_wrap.cv32e40p_wrapper_i.core_i.clk) begin
Can we make that `CV32E40P_CORE.clk`?  (The macro is defined at the top of the file.)

2021-05-02 11:20 UTC, eroom1966 commented on cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv
> +    always @(posedge uvmt_cv32e40p_tb.dut_wrap.cv32e40p_wrapper_i.core_i.clk) begin
Aah, sorry missed that - changing it to the MACRO is fine.

2021-05-02 11:21 UTC, eroom1966 commented on cv32e40p/tb/core/mm_ram.sv
> +            uvmt_cv32e40p_tb.iss_wrap.ram.RND_STALL = data_rdata_mux;
I was putting this in as forward planning, I recall something @strichmo mentioned that when stalls were in play the RTL/RM did not stay in sync.
I think anything with backdoor access, has to notify the RM memory.

2021-05-02 11:22 UTC, eroom1966 commented on cv32e40p/tb/core/mm_ram.sv
> +            uvmt_cv32e40p_tb.iss_wrap.ram.RND_NUM = data_rdata_mux;
again as above

2021-05-02 14:49 UTC, MikeOpenHWGroup commented on cv32e40p/tb/core/mm_ram.sv
> +            uvmt_cv32e40p_tb.iss_wrap.ram.RND_STALL = data_rdata_mux;
Good thinking.

2021-05-02 14:53 UTC, MikeOpenHWGroup commented on cv32e40p/tb/uvmt/uvmt_cv32e40p_step_compare.sv
> +    always @(posedge uvmt_cv32e40p_tb.dut_wrap.cv32e40p_wrapper_i.core_i.clk) begin
No worries, that's what PR reviews are for.  :-)  Seriously, I am rapidly becoming quite the fan of this workflow.

Can you push in a change to use the macro?

2021-05-07 11:46 UTC, MikeOpenHWGroup approved these changes

2021-05-07 11:46 UTC, merged