add support for minstret(h) from REF -> DUT Compare
openhwgroup/core-v-verif pull request #625
Opened 2021-05-24 13:25 UTC by eroom1966

This PR Adds full support for minstret prediction, propagated to a GPR bia a CSR read instruction

2021-05-25 13:31 UTC, MikeOpenHWGroup reviewed
Looks good @eroom1966.   Before approving I'd like to resolve the review I started on  `cv32e40p/vendor_lib/imperas/riscv_CV32E40P_OVPsim/sv/riscv_CV32E40X.sv `.   @strichmo, do you have an opinion?

2021-05-25 13:31 UTC, MikeOpenHWGroup commented on cv32e40p/vendor_lib/imperas/riscv_CV32E40P_OVPsim/sv/riscv_CV32E40X.sv
> +/*
Hi @eroom1966, I wonder if this file shouldn't be located someplace else such as `cv32e40x/vendor_lib/imperas/riscv_CV32E40P_OVPsim/sv/riscv_CV32E40X.sv`?

2021-05-25 16:38 UTC, strichmo requested changes

2021-05-25 16:38 UTC, strichmo commented on cv32e40p/vendor_lib/imperas/riscv_CV32E40P_OVPsim/sv/riscv_CV32E40P.sv
> -        if ($test$plusargs("USE_ISS")) begin
The if ($test$plusargs("USE_ISS")) code needs to be there to facilitate run-time disablement of the ISS for certain tests.

Is there another reason this was removed (i.e. was it breaking something)?

2021-05-25 16:40 UTC, strichmo commented on cv32e40p/vendor_lib/imperas/riscv_CV32E40P_OVPsim/sv/riscv_CV32E40X.sv
> +/*
Yes, it should be on the CV32E40X branch?

I'm a bit confused with this update as it appears that riscv_CV32E40X.sv and riscv_CV32E40P.sv have different sets of interfaces (The X version has updated RVVIs to incorporate interrupt, debug, etc.).  Is the intention to ensure that E40P and E40X ISS models are compatible with the newer interface definitions?

2021-07-21 16:29 UTC, eroom1966 commented
@MikeOpenHWGroup 
I think this PR is no longer valid - am I correct, if so I will close ?

2021-07-21 17:10 UTC, strichmo commented
I believe this PR should be closed without merging as well.

2021-07-21 23:07 UTC, MikeOpenHWGroup commented
Agree.  The PR is now very stale and has multiple conflicts.

2021-07-22 07:33 UTC, eroom1966 commented
closing as no longer relevant

2021-07-22 07:33 UTC, closed without merging