Reinstate debug assertions
openhwgroup/core-v-verif pull request #767
Opened 2021-08-04 09:32 UTC by silabs-robin

This PR re-enables 40x' debug assertions, re-wiring some connections and re-writing some of the assertions.

It passes in both sim and formal (NB! Needs assumes to limit obi wait states).
Though it is not fully 100% complete, most of it has been restored.
This should be thoroughly reviewed, and I will try to assist in that. Don't hold back any criticism or questions.
I already suspect that some changes are necessary, but I don't know what the right call is.

@silabs-oysteink

2021-08-04 09:35 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
>        .depc_q(dut_wrap.cv32e40x_wrapper_i.core_i.cs_registers_i.dpc_q),
About signal names in the interface (like "depc"), I think fixing that could wait?
The debug coverage must also be brought back, so I was thinking about doing a proper cleanup of all the signals then, to also purge any no-longer-needed signals.
Does that make sense or should it be done differently?

2021-08-04 09:42 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        |-> decode_valid [->1:20] ##0 cov_assert_if.debug_mode_q;
This was changed from `[->1:2]` to `[->1:20]` because obi could just stall indefinitely and deny debug entry.
This goto condition was confusing throughout the assertion set, so I would like to discuss what the best solution is.

From before, I think `1:2` represented the "currently executing ID" and "next arising execution in ID"? But now the decisions are being taken from WB so the conditions must necessarily change.
One proposal (that is implemented in some of the other assertions), is to use this:
`!decode_valid [->1] ##0 decode_valid [->1]`
to mean "wait til the current execution is done, then wait til we have continued again".

2021-08-04 09:54 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
>      property p_cebreak_exception;
This property is particularly difficult to capture.
The intent is to check _"c.ebreak without dcsr.ebreakm results in exception at mtvec"_, but that statement is not universally true without qualifications? Formal showed that an intercepting haltreq or irq could break that assertion.

Hence I added "throughout" conditions for not seeing haltreq or irq until we have arrived at the next execution.

One challenge here is to not over-constrain the antecedent, so that we "semi-vacuously" passes certain cases. But we also don't want a "liberal" consequent with some "||" that could falsely excuse real problems.

2021-08-04 09:59 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        // TODO:ropeders need assertions for what happens if cebreak and req/irq?
>         // TODO:ropeders need assertions for what happens if cebreak and req/irq?

Since haltreq and irq is excluded from the case above, I wonder if we should add new assertions that explicitly check such cases.

2021-08-04 10:00 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
>      property p_ebreak_exception;
Same problem**s** as with cebreak exception above.

2021-08-04 10:08 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        |-> !decode_valid [->1] ##0 decode_valid [->1]
Note:
Using `decode_valid` in the "consequent" is much safer (imo) than having it in the antecedent.
The antecedent should have as few constraints as possible, so we don't accidentally over-constrain and ignore cases that we actually wanted to consider.
The consequent could (imo) have as many "&&" factors as we want, because we will(?) be corrected if we expect too much (but "||" terms seem really dangerous to me).

2021-08-04 10:11 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        |-> !decode_valid [->1] ##0 decode_valid [->1]
But... Gotos in consequent might skip past some critical point, so the "&&"ing should be pretty rigorous and demanding.

2021-08-04 10:13 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
>      property p_sleep_debug_req;
Originally, there was 2 implications in this property. Was there some particular reason for that that I failed to heed?

2021-08-04 10:19 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
> +      .is_decoding(1),  //dut_wrap.cv32e40x_wrapper_i.core_i.is_decoding),  // TODO:ropeders figure out correct source
The signal is_decoding does not exist in RTL anymore, and cases using that signal within these assertions should probably change to look at the WB stage instead.

2021-08-04 10:20 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +    cov_assert_if.is_decoding
Could remove this signal, is_decoding does not exist in RTL anymore.

2021-08-04 10:20 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv
>      input         is_decoding,
Remove

2021-08-04 10:22 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +  assign decode_valid = cov_assert_if.id_stage_instr_valid_i && (cov_assert_if.ctrl_fsm_cs == cv32e40x_pkg::FUNCTIONAL);
Old controller made decisions based on state of the ID stage. New controller looks at WB (except for jumps in ID and branhces in EX), so I think that the assertions should probably only look at WB stage signals if possible

2021-08-04 10:30 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        |-> decode_valid [->1:20] ##0 cov_assert_if.debug_mode_q;
I would prefer if WB signals were used. The intention of the original assertion was that if a change in predicted debug case was seen, the next decoded instruction should be in debug mode.

2021-08-04 11:12 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> -        $rose(first_debug_ins) |-> cov_assert_if.debug_mode_q && (prev_id_pc == halt_addr_at_entry) && (cov_assert_if.depc_q == pc_at_dbg_req);
Should prev_id_pc really be used here?

2021-08-04 11:13 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        |-> cov_assert_if.debug_mode_q && (prev_id_pc == halt_addr_at_entry);
Should prev_id_pc really be used here?

2021-08-04 11:14 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
>      property p_cebreak_exception;
Yes, this is a hard case as there are so many other events that take priority over an ebreak without dcsr.ebreakm set.

2021-08-04 11:15 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        // TODO:ropeders need assertions for what happens if cebreak and req/irq?
I agree, we should probably have separate asserts for that.

2021-08-04 11:16 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        |-> !decode_valid [->1] ##0 decode_valid [->1]
I would prefer WB signals here too

2021-08-04 11:16 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        ##0 cov_assert_if.debug_mode_q && (cov_assert_if.id_stage_pc == halt_addr_at_entry);
.. and here, why id_stage_pc?

2021-08-04 11:17 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        ##0 cov_assert_if.debug_mode_q && (cov_assert_if.id_stage_pc == halt_addr_at_entry);
id_stage_pc again

2021-08-04 11:18 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        ##0 cov_assert_if.debug_mode_q && (cov_assert_if.id_stage_pc == exception_addr_at_entry);
Much ID stage above

2021-08-04 11:18 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        && cov_assert_if.is_decoding && cov_assert_if.id_stage_instr_valid_i
is_decoding not in RTL anymore

2021-08-04 11:19 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +    cov_dmode_dret_pc : cover property(s_dmode_dret_pc_ante |-> s_dmode_dret_pc_conse ##0 (cov_assert_if.depc_q != 0));
The reason I split `property` into two `sequence`s is because I wanted to check this cover. It was not obvious whether the assertion was just trivially passing or not.
If this style is difficult to read I am ok with changing it.

2021-08-04 11:21 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        ##1 (!cov_assert_if.debug_req_i && !cov_assert_if.irq_ack_o throughout decode_valid[->1]);
Interrupts are ignored during debug mode, so irq_ack_o should always be 0. No harm done in leaving it in though

2021-08-04 11:24 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +    // TODO:ropeders what is missing from these dret assertions?
>     // TODO:ropeders what is missing from these dret assertions?

Formal showed that the original assertion could be broken with intervening re-entry or interrupts. Therefore I tried to split the checking into multiple assertions, but I have a feeling that maybe not all cases are checked and there should be added some assertions.

2021-08-04 11:28 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +            if((cov_assert_if.ctrl_fsm_cs == cv32e40x_pkg::FUNCTIONAL) && !cov_assert_if.debug_mode_q) begin
Her you should be able to check if ctrl_fsm_ns == DEBUG_TAKEN and not in debug mode

2021-08-04 11:29 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
> +      .id_stage_wfi_insn     (dut_wrap.cv32e40x_wrapper_i.core_i.id_stage_i.id_ex_pipe_o.wfi_insn),  // TODO:ropeders "ex_stage"?
The id_ex_pipe_o.wfi_insn indicates WFI in EX as your comment suggests

2021-08-04 11:31 UTC, silabs-oysteink requested changes
In general I would like to remove most depencies on ID stage signals where possible.

2021-08-05 11:36 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
> +      .is_decoding(1),  //dut_wrap.cv32e40x_wrapper_i.core_i.is_decoding),  // TODO:ropeders figure out correct source
Fixed.

2021-08-05 11:37 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +    cov_assert_if.is_decoding
Fixed.

2021-08-05 11:38 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb_ifs.sv
>      input         is_decoding,
Fixed.

2021-08-05 22:37 UTC, strichmo commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
>        .depc_q(dut_wrap.cv32e40x_wrapper_i.core_i.cs_registers_i.dpc_q),
That makes sense to me.

2021-08-05 22:38 UTC, strichmo requested changes
When I pulled this PR in to test I had to move the *started_decoding_in_debug* logic delcaration slightly higher in the file to avoid a compile error.

```
     // Detect first instruction of debug code
+    logic started_decoding_in_debug;
 
     assign first_debug_ins =
         cov_assert_if.debug_mode_q && cov_assert_if.wb_valid
         && !first_debug_ins_flag && started_decoding_in_debug;
 
-    logic started_decoding_in_debug;
```

2021-08-06 07:28 UTC, silabs-robin commented
@strichmo 

> When I pulled this PR in to test I had to move the _started_decoding_in_debug_ logic delcaration slightly higher in the file to avoid a compile error.

Aha. That makes sense.
I think it was unfortunate timing that your checkout happened just after I made some commits trying to fix Øystein's feedback and I have only tested with Jasper.
I must make sure (once again, after adding new commits) that simulation runs ok before merge.

> Otherwise this PR looks OK to me.

That is good. I must still iron out some kinks, addressing all of Øystein's feedback.

2021-08-09 09:43 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
> +      .id_stage_wfi_insn     (dut_wrap.cv32e40x_wrapper_i.core_i.id_stage_i.id_ex_pipe_o.wfi_insn),  // TODO:ropeders "ex_stage"?
Will likely leave this as is for now, and fix when doing the coverage.

2021-08-09 09:53 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +            if((cov_assert_if.ctrl_fsm_cs == cv32e40x_pkg::FUNCTIONAL) && !cov_assert_if.debug_mode_q) begin
Let me see if I understood that correctly.

First there was:
```
if(cov_assert_if.ctrl_fsm_cs == cv32e40x_pkg::DECODE & !cov_assert_if.debug_mode_q) begin
    ...
end else if(cov_assert_if.ctrl_fsm_cs == cv32e40x_pkg::DBG_TAKEN_IF) begin
    ...
```

Now it is:
```
if((cov_assert_if.ctrl_fsm_cs == cv32e40x_pkg::FUNCTIONAL) && !cov_assert_if.debug_mode_q) begin
    ...
```

You propose(?):
```
if((cov_assert_if.ctrl_fsm_ns == DEBUG_TAKEN) && !cov_assert_if.debug_mode_q) begin
```

Would that be better?
Using FUNCTIONAL (as it is now) has the risk of accidentally updating the prediction in between DEBUG_TAKEN and entry, but we have not seen that it is possible?
Using DEBUG_TAKEN (as proposed) updates less often, so it risks missing cases?

2021-08-10 09:23 UTC, silabs-robin commented
This part needs careful review.

```
    sequence s_conse_next_retire;  // Should only be used in consequent (not antecedent)
        ($fell(cov_assert_if.wb_stage_instr_valid_i) [->1]  // Finish current preoccupation
            ##0 cov_assert_if.wb_valid [->1])  // Go to next WB done
        or
        (cov_assert_if.wb_valid [->1]  // Go directly to next WB done
            ##0 (cov_assert_if.dcsr_q[8:6] == 3))  // Need good reason to forgo $fell(instr_valid)
        ;
    endsequence
```

Explanation:
In the consequents (of `antecedent |-> consequent`), there was previously used `decode_valid[->1:2]` etc.
It is not straight forward to substitute it with `wb_valid[->1]` because of halt/kill signals etc.
I made this sequence, which is intended as a way to go to the cycle where our consequent should have its effect.
My worry is that it potentially can excuse bad behavior.
Example: I previously experimented with `debug_req[->1] ##0 wb_valid[->1]` but this seems bad, because an antecedent could fail our expectations but formal can potentially create a debug_req to make up for it.

2021-08-10 14:20 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        // TODO:ropeders need assertions for what happens if cebreak and req/irq?
@silabs-oysteink do you think that such new assertions should be made as part of this PR?

2021-08-11 07:09 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        ##0 $stable(cov_assert_if.tdata1) [*4];
@silabs-oysteink could you provide some more insight into this? I couldn't see this assertion in the vplan and I don't know the uarch well enough.
Do you think there is any reason to continue using id_stage?
Do you think the stability criterion should be different?

2021-08-17 07:06 UTC, silabs-robin commented
Hi @silabs-oysteink and @strichmo . I think the PR is ready to be merged now.
I updated it to work with the latest cv32e40x/dev, and both formal and simulation passes.
The only things outstanding are those comments above and that which I have started fixing as part of the debug coverage task.

2021-08-17 07:25 UTC, silabs-oysteink commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_debug_assert.sv
> +        ##0 $stable(cov_assert_if.tdata1) [*4];
The purpose of this assertion is to check that one cannot write to tdata1 outside of debug mode. As the 40X now does CSR writes in WB, WB signals should be used. I'm not sure about the stability criteria though, it should be enough to check stability before/after the actual (attempted) write.

2021-08-17 11:32 UTC, silabs-oysteink approved these changes

2021-08-17 11:33 UTC, silabs-robin commented
Sorry about the noise, but I remembered one potential problem!
The OBI "err" signal was reintroduced in core-v-verif, and since there is special handling of wb_valid in rtl/rvfi I disabled "err" in formal. This means that the assertions _can fail(!)_ if an obi "err" signal comes at the right time.
If we know that random tests used in regressions do not introduce "err" then I think there will be no problems from merging this, but if they do then a solution must be found first.

2021-08-20 01:17 UTC, strichmo approved these changes

2021-08-20 01:18 UTC, merged