Renamed rvfi debug signal to match cv32e40x update
openhwgroup/core-v-verif pull request #800
Opened 2021-08-11 14:28 UTC by silabs-halfdan

This pull request renames the rvfi_dbg signal to match updated naming in https://github.com/openhwgroup/cv32e40x/pull/177

Signed-off-by: Halfdan Bechmann <halfdan.bechmann@silabs.com>

2021-08-11 14:59 UTC, Silabs-ArjanB requested changes

2021-08-11 14:59 UTC, Silabs-ArjanB commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
> +                                                                   .rvfi_dbg(rvfi_i.rvfi_debug[0]),
No renaming like this between pin and signal. Also rvfi_debug will not longer exist in RVFI module

2021-08-13 13:11 UTC, strichmo commented
Added a DO NOT MERGE.  We need a few more changes to the RVFI core-side then we will revisit this PR (or replace as need be).

2021-08-18 12:44 UTC, silabs-halfdan commented
Closing this PR and opening a new one (#817) for cleaner git history.

2021-08-18 12:44 UTC, closed without merging