Adding fixes to heartbeat monitor
openhwgroup/core-v-verif pull request #833
Opened 2021-08-28 16:15 UTC by datum-dpoulin

Added performance improvements and documented the codebase.

2021-08-29 14:50 UTC, MikeOpenHWGroup reviewed
Thanks for this @datum-dpoulin.  I have reviewed the changes and left a couple of comments/questions.  Please have a look at those.

I am running a local regression which looks fine so far and I do expect it to pass (will add a comment once it has completed).

@strichmo, you orginated the issue on this (#727), so you should be the one to approve this PR.

2021-08-29 14:50 UTC, MikeOpenHWGroup commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +            timestamps.delete(ii);
Soooo, lemme see if I got this right: `timestamps` has been redefined as an associative array (was a queue).  I would expect this to result in modest memory savings.  The big change is that the "matured" timestamps are deleted from the array and _not_ pushed onto another queue.  This is where the memory savings are.  Do I have that right?

2021-08-29 14:50 UTC, MikeOpenHWGroup commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +   	id = $urandom();
Does this need to be random?   Why not define `id` as a static member which is simply incremented each time a new one is needed?

2021-08-29 15:12 UTC, datum-dpoulin commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_pkg.flist.xsim
> +-i ${DV_UVML_HRTBT_PATH}
Sure thing! I couldn't remember if we still had the special xsim versions anymore. Good catch. Definitely one thing we gotta get them away from.

2021-08-29 15:13 UTC, datum-dpoulin commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +            timestamps.delete(ii);
Yes I was copying all timestamps every time. Not sure why. This just deletes individual entries in an associative array.

2021-08-29 15:14 UTC, datum-dpoulin commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +   	id = $urandom();
It was already random, I didn't wanna change things.

2021-08-29 16:10 UTC, MikeOpenHWGroup commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +   	id = $urandom();
OK, at some point this should be discussed.  Results from $urandom() calls are not constrainable.

2021-08-29 16:11 UTC, MikeOpenHWGroup commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_pkg.flist.xsim
> +-i ${DV_UVML_HRTBT_PATH}
Great.  Please push in an update that removes this file.   Thanks.

2021-08-29 16:13 UTC, MikeOpenHWGroup reviewed
Note: my local regression passed (as expected).

2021-09-03 14:12 UTC, strichmo requested changes

2021-09-03 14:12 UTC, strichmo commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +function void uvml_hrtbt_mon_c::heartbeat(uvm_component owner, int unsigned id=0);
This method should bail out (without registering anything) if the heartbeat monitor is disabled.  This should alleviate the memory usage issues in any tests that may not want to use these.

2021-09-03 14:12 UTC, strichmo commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +         `uvm_info("HRTBT_MON", "Heartbeat count is 0. Dropping objection", UVM_NONE)
This can clutter logs.  Would prefer a higher verbosity level (UVM_HIGH)

2021-09-03 18:36 UTC, datum-dpoulin commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +function void uvml_hrtbt_mon_c::heartbeat(uvm_component owner, int unsigned id=0);
Excellent point Steve, I will add this in.

2021-09-03 18:39 UTC, datum-dpoulin commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_mon.sv
> +         `uvm_info("HRTBT_MON", "Heartbeat count is 0. Dropping objection", UVM_NONE)
I agree, with the exception of phases in which heartbeats were actually monitored. Then I'd put it at UVM_MEDIUM/LOW.

2021-09-03 19:54 UTC, strichmo approved these changes
Thanks for the fixes.

2021-09-03 21:41 UTC, datum-dpoulin commented on lib/uvm_libs/uvml_hrtbt/uvml_hrtbt_pkg.flist.xsim
> +-i ${DV_UVML_HRTBT_PATH}
Crap, I forgot to get rid of it I think.

2021-09-05 23:07 UTC, merged