Debug coverage update
openhwgroup/core-v-verif pull request #834
Opened 2021-08-31 14:54 UTC by silabs-robin

Coverage class updated to new controller.

Debug coverage is re-enabled (upon COV=1), and covergroups have been slightly updated.
In addition, unused signals were removed from the interface and some signals got updated.
(There are also a few lines of whitespace fixes that I couldn't resist.)

Both formal and simulation tests are passing (ps, the cov model itself is not used in formal).
I synced with upstream cv32e40x/dev and resolved the conflicts.
On the "debug_test" it shows 90.61%, but I have not tried to merge coverage results from several other tests.

@silabs-oysteink  I think your eyes would be valuable on the assertions file and the tb connections.

2021-09-01 18:30 UTC, strichmo requested changes
Please review single comment.  I don't consider it a must-fix.

2021-09-01 18:30 UTC, strichmo commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
>        .rst_ni(clknrst_if.reset_n),
Could we push this instance a bit down into the hierarchy (perhaps at the wrapper level)?  It might make the signal paths a bit easier to read.

2021-09-02 12:07 UTC, silabs-robin commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
>        .rst_ni(clknrst_if.reset_n),
Fixed.
I changed it to use "bind" for both the interface instantiation and for the assertions.
Simulation still generates a sensible db and it passes debug_test, and formal shows that assertions are still checked.

2021-09-02 12:13 UTC, strichmo commented on cv32e40x/tb/uvmt/uvmt_cv32e40x_tb.sv
>        .rst_ni(clknrst_if.reset_n),
Thanks!

2021-09-02 12:13 UTC, strichmo approved these changes

2021-09-02 12:14 UTC, strichmo commented
I'm good for merge when @silabs-oysteink is OK as well.

2021-09-03 06:02 UTC, silabs-oysteink approved these changes

2021-09-03 13:05 UTC, merged