add OBI D error monitoring and injection
openhwgroup/core-v-verif pull request #878
Opened 2021-09-16 21:06 UTC by strichmo

Also updates the RTL hash on to E40X

Enables replications of issues with OBI D NMI handler entry

2021-09-17 11:57 UTC, MikeOpenHWGroup requested changes
Interesting.  It appears that you are either taking advantage of, or compensating for, know behaviour of the RM - is that the case?

I asked for a couple of minor cleanups before merging.

2021-09-17 11:57 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_obi_seq.sv
> +      //#0.1ns;
Unless this is still needed, recommend it be removed before merging.

2021-09-17 11:57 UTC, MikeOpenHWGroup commented on lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_obi_seq.sv
> +      //$display("popped: %s", trn.access_type.name());
Same here: recommend removing all calls to $display() before merging, or re-coding as uvm_info().

2021-09-17 15:48 UTC, strichmo commented
Thanks for review @MikeOpenHWGroup 
Moving this to a draft and setting DO NOT MERGE.  

Lee is pushing in a need update to OVPSIM and then I will address the above and clean up the PR to get to a clean data bus directed test.

2021-09-20 16:45 UTC, strichmo commented on lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_obi_seq.sv
> +      //#0.1ns;
cleaned up

2021-09-20 16:45 UTC, strichmo commented on lib/uvm_agents/uvma_rvvi_ovpsim/seq/uvma_rvvi_ovpsim_obi_seq.sv
> +      //$display("popped: %s", trn.access_type.name());
Cleaned up

2021-09-27 13:33 UTC, strichmo commented
Dropping this branch.  The work will be merged into a future branch released in combination with the OVPSIM modeling update.

2021-09-27 13:33 UTC, closed without merging