Verissimo ruleset integration
openhwgroup/core-v-verif pull request #891
Opened 2021-09-23 10:17 UTC by gabrielrad

@MikeOpenHWGroup these are the two files needed by Verissimo.

2021-09-23 12:52 UTC, MikeOpenHWGroup requested changes
Thanks for this @gabrielrad.  Can I request a `README.md` in this directory to give other members of the community a bit of a explainer about Verissimo and the purpose of the ruleset and waivers file?  It need not be long and could probably include a link to the lint report.

2021-09-23 13:40 UTC, gabrielrad commented
That's a good idea, I'll ping you when it's done

2021-09-27 15:01 UTC, MikeOpenHWGroup approved these changes

2021-09-27 15:01 UTC, MikeOpenHWGroup commented
Thanks @gabrielrad!

2021-09-27 15:02 UTC, merged